//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 617.107.0.0.0
//

#ifndef BSUICAPackageView_h
#define BSUICAPackageView_h
@import Foundation;

#include "CAStateControllerDelegate-Protocol.h"

@class CALayer, CAStateController, UIView;

@interface BSUICAPackageView : UIView <CAStateControllerDelegate> {
    /* instance variables */
    struct CGSize { double width; double height; } _originalSize;
    id /* block */ _pendingCompletion;
    NSString *_pendingCompletionFromState;
    NSString *_pendingCompletionToState;
    NSDictionary *_publishedObjectMap;
    CALayer *_rootLayer;
    CAStateController *_stateController;
    NSObject<CAStateControllerDelegate> *_stateControllerDelegate;
}

@property (readonly, copy, nonatomic) NSArray *publishedObjectNames;
@property (weak, nonatomic) NSObject<CAStateControllerDelegate> *stateControllerDelegate;

/* instance methods */
- (id)initWithPackageName:(id)name inBundle:(id)bundle;
- (id)initWithURL:(id)url;
- (void)layoutSubviews;
- (id)publishedObjectNames;
- (id)publishedObjectWithName:(id)name;
- (_Bool)setState:(id)state;
- (_Bool)setState:(id)state animated:(_Bool)animated;
- (_Bool)setState:(id)state animated:(_Bool)animated transitionSpeed:(double)speed completion:(id /* block */)completion;
- (_Bool)setState:(id)state onLayer:(id)layer animated:(_Bool)animated transitionSpeed:(double)speed completion:(id /* block */)completion;
- (void)setStateControllerDelegate:(id)delegate;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)stateController:(id)controller didSetStateOfLayer:(id)layer;
- (void)stateController:(id)controller transitionDidStart:(id)start speed:(float)speed;
- (void)stateController:(id)controller transitionDidStop:(id)stop completed:(_Bool)completed;
- (id)stateControllerDelegate;

@end

#endif /* BSUICAPackageView_h */