//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 1045.15.0.0.0
//

#ifndef CAPackage_h
#define CAPackage_h
@import Foundation;

#include "CALayer.h"

@interface CAPackage : NSObject {
    /* instance variables */
    struct _CAPackageData { id x0; id x1; id x2; _Bool x3; _Bool x4; id x5; id x6; } * _data;
}

@property (readonly) _Bool geometryFlipped;
@property (readonly) CALayer *rootLayer;

/* class methods */
+ (id)packageWithContentsOfURL:(id)url type:(id)type options:(id)options error:(id *)error;
+ (id)packageWithData:(id)data type:(id)type options:(id)options error:(id *)error;

/* instance methods */
- (Class)CAMLParser:(id)camlparser didFailToFindClassWithName:(id)name;
- (void)CAMLParser:(id)camlparser didLoadResource:(id)resource fromURL:(id)url;
- (id)CAMLParser:(id)camlparser resourceForURL:(id)url;
- (void)_addClassSubstitutions:(id)substitutions;
- (id)_initWithContentsOfURL:(id)url type:(id)type options:(id)options error:(id *)error;
- (id)_initWithData:(id)data type:(id)type options:(id)options error:(id *)error;
- (void)_readFromArchiveData:(id)data options:(id)options error:(id *)error;
- (void)_readFromCAMLData:(id)camldata type:(id)type options:(id)options error:(id *)error;
- (void)_readFromCAMLURL:(id)camlurl type:(id)type options:(id)options error:(id *)error;
- (void)dealloc;
- (void)foreachLayer:(id /* block */)layer;
- (_Bool)isGeometryFlipped;
- (id)publishedObjectNames;
- (id)publishedObjectWithName:(id)name;
- (id)rootLayer;
- (id)substitutedClasses;
- (Class)unarchiver:(id)unarchiver cannotDecodeObjectOfClassName:(id)name originalClasses:(id)classes;
- (id)unarchiver:(id)unarchiver didDecodeObject:(id)object;

@end

#endif /* CAPackage_h */