//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 1045.15.0.0.0
//

#ifndef CAStateController_h
#define CAStateController_h
@import Foundation;

#include "CALayer.h"

@protocol CAStateControllerDelegate;

@interface CAStateController : NSObject {
    /* instance variables */
    struct _CAStateControllerData { id x0; struct __CFDictionary *x1; id x2; id x3; } * _data;
}

@property (weak) NSObject<CAStateControllerDelegate> *delegate;
@property (readonly) CALayer *layer;

/* instance methods */
- (void)_addAnimation:(id)animation forKey:(id)key target:(id)target undo:(id)undo;
- (void)_applyTransition:(id)transition layer:(id)layer undo:(id)undo speed:(float)speed;
- (void)_applyTransitionElement:(id)element layer:(id)layer undo:(id)undo speed:(float)speed;
- (void)_nextStateTimer:(id)timer;
- (void)_removeTransition:(id)transition layer:(id)layer;
- (void)cancelTimers;
- (void)dealloc;
- (id)delegate;
- (id)initWithLayer:(id)layer;
- (id)layer;
- (id)removeAllStateChanges;
- (void)restoreStateChanges:(id)changes;
- (void)setDelegate:(id)delegate;
- (void)setInitialStatesOfLayer:(id)layer;
- (void)setInitialStatesOfLayer:(id)layer transitionSpeed:(float)speed;
- (void)setState:(id)state ofLayer:(id)layer;
- (void)setState:(id)state ofLayer:(id)layer transitionSpeed:(float)speed;
- (id)stateOfLayer:(id)layer;

@end

#endif /* CAStateController_h */