//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 1045.15.0.0.0
//

#ifndef CAState_h
#define CAState_h
@import Foundation;

@interface CAState : NSObject <NSCopying, NSSecureCoding> {
    /* instance variables */
    NSString *_basedOn;
    NSMutableArray *_elements;
    _Bool _enabled;
    _Bool _initial;
    _Bool _locked;
    NSString *_name;
    double _nextDelay;
    double _previousDelay;
}

@property (copy) NSString *basedOn;
@property (copy, nonatomic) NSArray *elements;
@property _Bool enabled;
@property _Bool initial;
@property (nonatomic) _Bool locked;
@property (copy, nonatomic) NSString *name;
@property double nextDelay;
@property double previousDelay;

/* class methods */
+ (void)CAMLParserStartElement:(id)element;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)CAMLParser:(id)camlparser setValue:(id)value forKey:(id)key;
- (id)CAMLTypeForKey:(id)key;
- (void)addElement:(id)element;
- (id)basedOn;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)dealloc;
- (id)debugDescription;
- (id)elements;
- (void)encodeWithCAMLWriter:(id)camlwriter;
- (void)encodeWithCoder:(id)coder;
- (void)foreachLayer:(id /* block */)layer;
- (id)init;
- (id)initWithCoder:(id)coder;
- (_Bool)isEnabled;
- (_Bool)isInitial;
- (_Bool)isLocked;
- (id)name;
- (double)nextDelay;
- (double)previousDelay;
- (void)removeElement:(id)element;
- (void)setBasedOn:(id)on;
- (void)setElements:(id)elements;
- (void)setEnabled:(_Bool)enabled;
- (void)setInitial:(_Bool)initial;
- (void)setLocked:(_Bool)locked;
- (void)setName:(id)name;
- (void)setNextDelay:(double)delay;
- (void)setPreviousDelay:(double)delay;

@end

#endif /* CAState_h */