//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 4344.144.0.0.0
//

#ifndef CSBackgroundContentView_h
#define CSBackgroundContentView_h
@import Foundation;

#include "CSWallpaperView-Protocol.h"

@class UIView;
@protocol UIScenePresentation;

@interface CSBackgroundContentView : UIView <CSWallpaperView> {
    /* instance variables */
    UIView<UIScenePresentation> *_presentationView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) UIView<UIScenePresentation> *presentationView;
@property (readonly) Class superclass;

/* instance methods */
- (id)initWithPresentationView:(id)view;
- (void)layoutSubviews;
- (id)presentationView;
- (void)setBackgroundStyle:(long long)style;
- (void)setCoverSheetWallpaperStyle:(long long)style;
- (void)setFullscreen:(_Bool)fullscreen;

@end

#endif /* CSBackgroundContentView_h */