//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 4344.144.0.0.0
//

#ifndef CSCoverSheetViewController_h
#define CSCoverSheetViewController_h
@import Foundation;

#include "BCBatteryDeviceObserving-Protocol.h"
#include "BSInvalidatable-Protocol.h"
#include "CAAnimationDelegate-Protocol.h"
#include "CSActivityItemObserving-Protocol.h"
#include "CSActivityPickerViewControllerParentContainer-Protocol.h"
#include "CSAppearance.h"
#include "CSBackgroundContentActionManager.h"
#include "CSBackgroundContentActionManagerDelegate-Protocol.h"
#include "CSBackgroundContentViewController.h"
#include "CSBackgroundPresentationManager.h"
#include "CSBehavior.h"
#include "CSChargingViewController.h"
#include "CSCombinedListViewControllerVisibleBreakthoughContentObserver-Protocol.h"
#include "CSComplicationContainerViewController.h"
#include "CSComplicationContainerViewControllerDelegate-Protocol.h"
#include "CSComplicationManager.h"
#include "CSCoverSheetAppearanceResolver.h"
#include "CSCoverSheetGestureHandling-Protocol.h"
#include "CSCoverSheetView.h"
#include "CSCoverSheetViewControllerBase.h"
#include "CSCoverSheetViewControllerProtocol-Protocol.h"
#include "CSCoverSheetViewDelegate-Protocol.h"
#include "CSCoverSheetViewPresenting-Protocol.h"
#include "CSCoverSheetViewTransitionSource-Protocol.h"
#include "CSDateTimeLayoutAggregating-Protocol.h"
#include "CSDismissableModalViewController.h"
#include "CSEmbeddedContentActionManager.h"
#include "CSEmbeddedContentActionManagerDelegate-Protocol.h"
#include "CSExternalBehaviorProviding-Protocol.h"
#include "CSFaceOcclusionMonitor.h"
#include "CSFixedFooterViewController.h"
#include "CSFocusActivityViewController.h"
#include "CSHomeButtonShowPasscodeRecognizer.h"
#include "CSHomeButtonSuppressAfterUnlockRecognizer.h"
#include "CSInterstitialTransitionDelegate-Protocol.h"
#include "CSInterstitialTransitionSource.h"
#include "CSLayoutStrategy.h"
#include "CSLegibilityProviderDelegate-Protocol.h"
#include "CSLockScreenSettings.h"
#include "CSMagSafeAccessoryStatusDelegate-Protocol.h"
#include "CSMagSafeAccessoryStatusObserver.h"
#include "CSMagSafeAccessoryViewController.h"
#include "CSMainPageContentViewController.h"
#include "CSMainPageContentViewControllerMediaControlsObserver-Protocol.h"
#include "CSMainPageContentViewControllerNotificationObserver-Protocol.h"
#include "CSModalPresentationViewController.h"
#include "CSNotificationClearingTrigger.h"
#include "CSNotificationClearingTriggerDelegate-Protocol.h"
#include "CSNotificationDestination-Protocol.h"
#include "CSNotificationDispatcher-Protocol.h"
#include "CSNotificationDispatcher.h"
#include "CSOverrideNotificationListDisplayStyleAssertion.h"
#include "CSPasscodeViewControllerDelegate-Protocol.h"
#include "CSPersistentContentLayoutProviding-Protocol.h"
#include "CSPoseidonViewController.h"
#include "CSPosterSwitcherActivationManager.h"
#include "CSPosterSwitcherActivationManagerDelegate-Protocol.h"
#include "CSPosterSwitcherActivationSource-Protocol.h"
#include "CSPosterSwitcherTransitionDelegate-Protocol.h"
#include "CSPosterSwitcherTransitionSource.h"
#include "CSPosterSwitcherViewController.h"
#include "CSPowerChangeObserver.h"
#include "CSPresentation.h"
#include "CSPresentationViewController.h"
#include "CSPresentationViewControllerDelegate-Protocol.h"
#include "CSProudLockViewController.h"
#include "CSProudLockViewControllerDelegate-Protocol.h"
#include "CSQuickActionsViewController.h"
#include "CSRemoteContentInlineProviding-Protocol.h"
#include "CSRemoteContentInlineViewController.h"
#include "CSRemoteContentModalViewController.h"
#include "CSRemoteContentSessionHostDelegate-Protocol.h"
#include "CSRemoteContentSessionManager.h"
#include "CSScrollGestureController.h"
#include "CSScrollGestureControllerDelegate-Protocol.h"
#include "CSScrollablePageViewControllerDelegate-Protocol.h"
#include "CSTeachableMomentsContainerViewController.h"
#include "CSTimerViewController.h"
#include "CSTimerViewControllerDelegate-Protocol.h"
#include "CSUserPresenceMonitor.h"
#include "FBSDisplayLayoutPublisherObserving-Protocol.h"
#include "PBUIIrisWallpaperPlayerDelegate-Protocol.h"
#include "SBCoverSheetSpotlightPresenterDelegate-Protocol.h"
#include "SBFBacklightSceneHostEnvironmentProviding-Protocol.h"
#include "SBFDashBoardModalPresenterProtocol-Protocol.h"
#include "SBFOverlayDismissalDelegate-Protocol.h"
#include "SBFOverlayObserving-Protocol.h"
#include "SBLockScreenActionProvider-Protocol.h"
#include "SBNotificationDestination-Protocol.h"
#include "SBSearchGestureDelegate-Protocol.h"
#include "SBSearchGestureObserver-Protocol.h"
#include "SBUIPhoneUnlockWithWatchControllerDelegate-Protocol.h"
#include "SBUIPhoneUnlockWithWatchControllerObserver-Protocol.h"
#include "UICoordinateSpace-Protocol.h"
#include "UIGestureRecognizerDelegate-Protocol.h"
#include "_UISettingsKeyObserver-Protocol.h"

@class ACActivityCenter, BCBatteryDeviceController, BSAbsoluteMachTimer, BSUIVibrancyConfiguration, SBAlwaysOnDefaults, SBFLegacyWallpaperWakeAnimator, SBFLockScreenActionContext, SBFLockScreenDateSubtitleView, SBFLockScreenDateViewController, SBLockScreenDefaults, SBSearchGesture, SBSpotlightTransientOverlayInteractiveGestureTransaction, SBUIPhoneUnlockWithWatchController, SBWallpaperAggdLogger, UIGestureRecognizer, UILongPressGestureRecognizer, UINotificationFeedbackGenerator, UIStatusBar, UITapGestureRecognizer, UIView, _UILegibilitySettings;
@protocol CSApplicationLaunching, CSCameraPrewarming, CSCoverSheetContextProviding, CSCoverSheetSpotlightPresenting, CSCoverSheetViewControllerDelegate, CSEmergencyCalling, CSExternalEventHandling, CSIdleTimerControlling, CSLegibilityProviding, CSOrientationUpdateControlling, CSWallpaperColorProvider, CSWidgetURLHandling, PBUIIrisWallpaperPlaying, PBUIWallpaperPositioning, SBFLockOutStatusProvider, SBFOverlayControlling, SBFScreenWakeAnimationControlling, SBFScreenWakeAnimationTarget, SBSWidgetMetricsProviding;

@interface CSCoverSheetViewController : CSCoverSheetViewControllerBase <BCBatteryDeviceObserving, CAAnimationDelegate, CSActivityItemObserving, CSActivityPickerViewControllerParentContainer, CSBackgroundContentActionManagerDelegate, CSCombinedListViewControllerVisibleBreakthoughContentObserver, CSComplicationContainerViewControllerDelegate, CSCoverSheetGestureHandling, CSCoverSheetViewControllerProtocol, CSCoverSheetViewDelegate, CSCoverSheetViewTransitionSource, CSDateTimeLayoutAggregating, CSEmbeddedContentActionManagerDelegate, CSInterstitialTransitionDelegate, CSLegibilityProviderDelegate, CSMagSafeAccessoryStatusDelegate, CSMainPageContentViewControllerMediaControlsObserver, CSMainPageContentViewControllerNotificationObserver, CSNotificationClearingTriggerDelegate, CSNotificationDestination, CSPasscodeViewControllerDelegate, CSPersistentContentLayoutProviding, CSPosterSwitcherActivationManagerDelegate, CSPosterSwitcherActivationSource, CSPosterSwitcherTransitionDelegate, CSPresentationViewControllerDelegate, CSProudLockViewControllerDelegate, CSRemoteContentInlineProviding, CSRemoteContentSessionHostDelegate, CSScrollGestureControllerDelegate, CSScrollablePageViewControllerDelegate, CSTimerViewControllerDelegate, FBSDisplayLayoutPublisherObserving, PBUIIrisWallpaperPlayerDelegate, SBCoverSheetSpotlightPresenterDelegate, SBFBacklightSceneHostEnvironmentProviding, SBFDashBoardModalPresenterProtocol, SBFOverlayDismissalDelegate, SBFOverlayObserving, SBLockScreenActionProvider, SBSearchGestureDelegate, SBSearchGestureObserver, SBUIPhoneUnlockWithWatchControllerDelegate, SBUIPhoneUnlockWithWatchControllerObserver, UIGestureRecognizerDelegate, _UISettingsKeyObserver> {
    /* instance variables */
    double _accessibilityTimeLabelBaselineY;
    double _accessibilityTimeSubtitleBaselineY;
    CSMagSafeAccessoryStatusObserver *_accessoryAttachmentObserver;
    CSMagSafeAccessoryViewController *_accessoryViewController;
    BSAbsoluteMachTimer *_accessoryViewControllerChargingTimer;
    id /* block */ _accessoryViewControllerChargingTimerHandler;
    BSAbsoluteMachTimer *_accessoryViewControllerTimer;
    id /* block */ _accessoryViewControllerTimerHandler;
    _Bool _accessoryViewPresentationDelayed;
    CSAppearance *_activeAppearance;
    CSBehavior *_activeBehavior;
    CSPresentation *_activePresentation;
    ACActivityCenter *_activityCenter;
    CSFocusActivityViewController *_activityViewController;
    NSArray *_allowedPageViewControllers;
    SBAlwaysOnDefaults *_alwaysOnDefaults;
    CSCoverSheetAppearanceResolver *_appearanceResolver;
    NSHashTable *_applicationHosters;
    id <CSApplicationLaunching> _applicationLauncher;
    NSMutableArray *_attachedAccessories;
    _Bool _authenticated;
    CSBackgroundContentActionManager *_backgroundContentActionManager;
    UITapGestureRecognizer *_backgroundContentGestureRecognizer;
    CSBackgroundContentViewController *_backgroundContentViewController;
    CSBackgroundPresentationManager *_backgroundPresentationManager;
    double _backlightLevel;
    long long _backlightTransitionGeneration;
    BCBatteryDeviceController *_batteryDeviceController;
    _Bool _blockingPowerStatusTriggeredChargingUI;
    NSArray *_cachedBatteryDevices;
    id <CSCameraPrewarming> _cameraPrewarmer;
    SBFLockScreenDateSubtitleView *_chargingLabel;
    CSChargingViewController *_chargingViewController;
    BSAbsoluteMachTimer *_chargingViewControllerTimer;
    id /* block */ _chargingViewTimerHandler;
    double _complicationContainerHeight;
    CSComplicationContainerViewController *_complicationContainerViewController;
    CSComplicationManager *_complicationManager;
    UILongPressGestureRecognizer *_complicationSelectionRecognizer;
    _Bool _contentAboveIsControlCenter;
    _Bool _contentAboveIsSiriOrNotFullScreenOniPad;
    id <CSCoverSheetContextProviding> _coverSheetContext;
    id <CSCoverSheetSpotlightPresenting> _coverSheetSpotlightPresenter;
    NSString *_currentCoachingString;
    id <CSCoverSheetViewTransitionSource> _currentTransitionSource;
    SBFLockScreenActionContext *_customLockScreenActionContext;
    SBFLockScreenDateViewController *_dateViewController;
    NSDate *_defaultsDerivedOverrideDate;
    id <CSCoverSheetViewControllerDelegate> _delegate;
    _Bool _didDismissSinceScreenOn;
    _Bool _dismissed;
    id <CSNotificationDispatcher> _dispatcher;
    id <BSInvalidatable> _displayLayoutTransitionAssertion;
    long long _effectiveInterfaceOrientationOverride;
    BSUIVibrancyConfiguration *_effectiveVibrancyConfiguration;
    CSEmbeddedContentActionManager *_embeddedContentActionManager;
    id <CSEmergencyCalling> _emergencyCaller;
    NSMutableArray *_exemptFromInactiveAppearanceParticipants;
    NSHashTable *_externalAppearanceProviders;
    NSHashTable *_externalBehaviorProviders;
    NSHashTable *_externalEventHandlers;
    NSHashTable *_externalLockProviders;
    NSHashTable *_externalPresentationProviders;
    CSFaceOcclusionMonitor *_faceOcclusionMonitor;
    UIStatusBar *_fakeStatusBar;
    CSFixedFooterViewController *_fixedFooterViewController;
    UIView<BSInvalidatable, PBUIWallpaperPositioning> *_floatingLayerView;
    _Bool _hasContentAboveCoverSheet;
    _Bool _hasPresentedForInterstitialTransitionSource;
    CSHomeButtonShowPasscodeRecognizer *_homeButtonShowPasscodeRecognizer;
    CSHomeButtonSuppressAfterUnlockRecognizer *_homeButtonSuppressAfterUnlockRecognizer;
    id <CSIdleTimerControlling> _idleTimerController;
    double _initialInterstitialTransitionProgress;
    double _initialOverlayPresentationProgress;
    CSComplicationContainerViewController *_inlineComplicationContainerViewController;
    CSInterstitialTransitionSource *_interstitialTransitionSource;
    _Bool _interstitialTransitionStartedFromPasscodePresented;
    CSBehavior *_irisBehavior;
    _Bool _irisPlayerIsInteracting;
    id <PBUIIrisWallpaperPlaying> _irisWallpaperPlayer;
    _Bool _isAccessoryAnimationAllowed;
    _Bool _isAccessoryAnimationPresenting;
    _Bool _isRemovingLockScreenContentAction;
    CSComplicationContainerViewController *_landscapeInlineComplicationContainerViewController;
    int _lastAppearState;
    unsigned long long _lastSettledPageIndex;
    CSLayoutStrategy *_layoutStrategy;
    SBFLegacyWallpaperWakeAnimator *_legacyWallpaperWakeAnimator;
    id <CSLegibilityProviding> _legibilityProvider;
    _Bool _listeningForDisplayLayoutChanges;
    CSAppearance *_localAppearance;
    CSBehavior *_localBehavior;
    _Bool _lockOrientationWhileTransitioning;
    id <SBFLockOutStatusProvider> _lockOutController;
    SBLockScreenDefaults *_lockScreenDefaults;
    CSMainPageContentViewController *_mainPageContentViewController;
    CSModalPresentationViewController *_modalPresentationController;
    _Bool _needsAccessibilityContentSizesUpdate;
    CSNotificationClearingTrigger *_notificationClearingTrigger;
    CSNotificationDispatcher *_notificationDispatcher;
    NSHashTable *_observers;
    id <CSOrientationUpdateControlling> _orientationUpdateController;
    id <SBFOverlayControlling, CSExternalBehaviorProviding, CSExternalEventHandling> _overlayController;
    NSArray *_pageViewControllers;
    _Bool _partiallyOnScreen;
    long long _participantState;
    NSMutableSet *_pendingModalViewControllers;
    SBUIPhoneUnlockWithWatchController *_phoneUnlockWithWatchController;
    CSPoseidonViewController *_poseidonViewController;
    CSPosterSwitcherActivationManager *_posterSwitcherActivationManager;
    UINotificationFeedbackGenerator *_posterSwitcherFeedbackGenerator;
    UILongPressGestureRecognizer *_posterSwitcherGestureRecognizer;
    CSPosterSwitcherTransitionSource *_posterSwitcherTransitionSource;
    CSPosterSwitcherViewController *_posterSwitcherViewController;
    CSPowerChangeObserver *_powerChangeObserver;
    _Bool _preventAppearanceUpdatesForRotation;
    _Bool _preventStatusBarDateTimeUpdates;
    CSAppearance *_previousAppearance;
    CSLockScreenSettings *_prototypeSettings;
    CSProudLockViewController *_proudLockViewController;
    CSQuickActionsViewController *_quickActionsViewController;
    UITapGestureRecognizer *_quickNoteGestureRecognizer;
    NSMutableSet *_remoteContentInlineProvidingManagers;
    CSRemoteContentInlineViewController *_remoteContentInlineViewController;
    CSRemoteContentModalViewController *_remoteContentModalViewController;
    CSRemoteContentSessionManager *_remoteContentSessionManager;
    CSOverrideNotificationListDisplayStyleAssertion *_remoteOverrideNotificationDisplayStyleAssertion;
    _Bool _screenOffMode;
    _Bool _screenOnForLiftToWake;
    id <SBFScreenWakeAnimationControlling> _screenWakeAnimationController;
    CSScrollGestureController *_scrollGestureController;
    SBSearchGesture *_searchGesture;
    _Bool _shouldTransitionIrisWallpaperToStillWhenPlaybackFinishes;
    SBSpotlightTransientOverlayInteractiveGestureTransaction *_spotlightInteractiveGestureTransaction;
    CSDismissableModalViewController *_spotlightModalViewController;
    UIView *_statusBarBackgroundView;
    _Bool _statusBarInLockdownForTeardown;
    _Bool _suppressModalRemotePresentation;
    id <BSInvalidatable> _suspendWallpaperAnimationAssertion;
    CSTeachableMomentsContainerViewController *_teachableMomentsContainerViewController;
    CSTimerViewController *_timerViewController;
    struct { double value; struct { struct { double value; _Bool inclusive; } start; struct { double value; _Bool inclusive; } end; } interval; long long mode; } _transitionContext;
    long long _transitionContextMode;
    _Bool _transitionDisabledIdleTimer;
    long long _transitionType;
    CSUserPresenceMonitor *_userPresenceMonitor;
    BSUIVibrancyConfiguration *_vibrancyConfiguration;
    BSUIVibrancyConfiguration *_vibrancyConfigurationOverride;
    int _wakeSource;
    SBWallpaperAggdLogger *_wallpaperAggdLogger;
    id <CSWallpaperColorProvider> _wallpaperColorProvider;
    UIGestureRecognizer *_wallpaperGestureRecognizer;
    _Bool _wantsAccessibilityContentSizes;
    _Bool _wantsStatusBarLockItemDisabled;
    id <CSWidgetURLHandling> _widgetURLHandler;
}

@property (retain, nonatomic) CSMagSafeAccessoryStatusObserver *accessoryAttachmentObserver;
@property (copy, nonatomic) CSAppearance *activeAppearance;
@property (copy, nonatomic) CSBehavior *activeBehavior;
@property (retain, nonatomic) CSPresentation *activePresentation;
@property (retain, nonatomic) ACActivityCenter *activityCenter;
@property (copy, nonatomic) NSArray *allowedPageViewControllers;
@property (nonatomic) _Bool alternateDateEnabled;
@property (readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property (weak, nonatomic) id <CSApplicationLaunching> applicationLauncher;
@property (nonatomic) _Bool authenticated;
@property (nonatomic) double backlightLevel;
@property (readonly, nonatomic) long long backlightLuminance;
@property (retain, nonatomic) id <CSCameraPrewarming> cameraPrewarmer;
@property (retain, nonatomic) CSComplicationContainerViewController *complicationContainerViewController;
@property (readonly, copy, nonatomic) NSSet *components;
@property (readonly, nonatomic) _Bool contentOccludesBackground;
@property (readonly, nonatomic) id <CSCoverSheetContextProviding> coverSheetContext;
@property (readonly, copy, nonatomic) NSString *coverSheetIdentifier;
@property (weak, nonatomic) id <CSCoverSheetSpotlightPresenting> coverSheetSpotlightPresenter;
@property (readonly, nonatomic) CSCoverSheetView *coverSheetView;
@property (retain, nonatomic) id <CSCoverSheetViewTransitionSource> currentTransitionSource;
@property (readonly, nonatomic) double customIdleExpirationTimeout;
@property (readonly, nonatomic) double customIdleWarningTimeout;
@property (retain, nonatomic) SBFLockScreenActionContext *customLockScreenActionContext;
@property (retain, nonatomic) SBFLockScreenDateViewController *dateViewController;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <CSCoverSheetViewControllerDelegate> delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) _Bool didDismissSinceScreenOn;
@property (nonatomic) _Bool dismissed;
@property (weak, nonatomic) id <CSNotificationDispatcher> dispatcher;
@property (readonly, nonatomic) long long effectiveInterfaceOrientation;
@property (nonatomic) long long effectiveInterfaceOrientationOverride;
@property (retain, nonatomic) BSUIVibrancyConfiguration *effectiveVibrancyConfiguration;
@property (weak, nonatomic) id <CSEmergencyCalling> emergencyCaller;
@property (readonly, nonatomic) _Bool externalLockProvidersRequireUnlock;
@property (readonly, nonatomic) _Bool externalLockProvidersShowPasscode;
@property (readonly, copy, nonatomic) CSPresentation *externalPresentation;
@property (retain, nonatomic) UIStatusBar *fakeStatusBar;
@property (readonly, nonatomic) _Bool hasContentAboveCoverSheet;
@property (nonatomic) _Bool hasPresentedForInterstitialTransitionSource;
@property (readonly, nonatomic) _Bool hasVisibleContentToReveal;
@property (readonly) unsigned long long hash;
@property (weak, nonatomic) id <CSIdleTimerControlling> idleTimerController;
@property (readonly, nonatomic) long long idleTimerDuration;
@property (readonly, nonatomic) long long idleTimerMode;
@property (readonly, nonatomic) long long idleWarnMode;
@property (nonatomic) double initialOverlayPresentationProgress;
@property (retain, nonatomic) CSComplicationContainerViewController *inlineComplicationContainerViewController;
@property (retain, nonatomic) CSInterstitialTransitionSource *interstitialTransitionSource;
@property (retain, nonatomic) CSBehavior *irisBehavior;
@property (nonatomic) _Bool irisPlayerIsInteracting;
@property (retain, nonatomic) id <PBUIIrisWallpaperPlaying> irisWallpaperPlayer;
@property (readonly, nonatomic) _Bool isAccessoryAnimationPresenting;
@property (retain, nonatomic) CSComplicationContainerViewController *landscapeInlineComplicationContainerViewController;
@property (nonatomic) unsigned long long lastSettledPageIndex;
@property (retain, nonatomic) CSLayoutStrategy *layoutStrategy;
@property (readonly, nonatomic) id <SBFScreenWakeAnimationTarget> legacyWallpaperWakeAnimator;
@property (retain, nonatomic) id <CSLegibilityProviding> legibilityProvider;
@property (readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property (copy, nonatomic) CSAppearance *localAppearance;
@property (retain, nonatomic) CSBehavior *localBehavior;
@property (nonatomic) _Bool lockOrientationWhileTransitioning;
@property (retain, nonatomic) id <SBFLockOutStatusProvider> lockOutController;
@property (retain, nonatomic) CSMainPageContentViewController *mainPageContentViewController;
@property (readonly, nonatomic) CSPresentationViewController *mainPagePresentationViewController;
@property (retain, nonatomic) CSModalPresentationViewController *modalPresentationController;
@property (readonly, nonatomic) long long notificationBehavior;
@property (readonly, nonatomic) id <SBNotificationDestination> notificationDestination;
@property (retain, nonatomic) id <CSOrientationUpdateControlling> orientationUpdateController;
@property (retain, nonatomic) id <SBFOverlayControlling, CSExternalBehaviorProviding, CSExternalEventHandling> overlayController;
@property (copy, nonatomic) NSArray *pageViewControllers;
@property (nonatomic) _Bool partiallyOnScreen;
@property (readonly, nonatomic) long long participantState;
@property (retain, nonatomic) NSMutableSet *pendingModalViewControllers;
@property (retain, nonatomic) CSPosterSwitcherActivationManager *posterSwitcherActivationManager;
@property (retain, nonatomic) CSPosterSwitcherTransitionSource *posterSwitcherTransitionSource;
@property (retain, nonatomic) CSPosterSwitcherViewController *posterSwitcherViewController;
@property (retain, nonatomic) CSPowerChangeObserver *powerChangeObserver;
@property (readonly, nonatomic) long long presentationAltitude;
@property (readonly, weak, nonatomic) id <UICoordinateSpace> presentationCoordinateSpace;
@property (readonly, nonatomic) unsigned int presentationFrameRateRangeReason;
@property (readonly, nonatomic) struct CAFrameRateRange { float x0; float x1; float x2; } presentationPreferredFrameRateRange;
@property (readonly, nonatomic) long long presentationPriority;
@property (readonly, copy, nonatomic) NSArray *presentationRegions;
@property (readonly, nonatomic) long long presentationStyle;
@property (readonly, nonatomic) long long presentationTransition;
@property (readonly, nonatomic) long long presentationType;
@property (weak, nonatomic) id <CSCoverSheetViewPresenting> presenter;
@property (copy, nonatomic) CSAppearance *previousAppearance;
@property (readonly, nonatomic) long long proximityDetectionMode;
@property (readonly, nonatomic) _Bool restToOpenAvailable;
@property (readonly, nonatomic) unsigned long long restrictedCapabilities;
@property (retain, nonatomic) id <SBFScreenWakeAnimationControlling> screenWakeAnimationController;
@property (readonly, nonatomic) long long scrollingStrategy;
@property (retain, nonatomic) SBSearchGesture *searchGesture;
@property (readonly, nonatomic) _Bool shouldShowLockStatusBarTime;
@property (nonatomic) _Bool shouldTransitionIrisWallpaperToStillWhenPlaybackFinishes;
@property (nonatomic) _Bool showingMediaControls;
@property (retain, nonatomic) SBSpotlightTransientOverlayInteractiveGestureTransaction *spotlightInteractiveGestureTransaction;
@property (retain, nonatomic) UIView *statusBarBackgroundView;
@property (readonly) Class superclass;
@property (retain, nonatomic) id <BSInvalidatable> suspendWallpaperAnimationAssertion;
@property (retain, nonatomic) CSTimerViewController *timerViewController;
@property (readonly, nonatomic) struct { double x0; struct { struct { double x0; _Bool x1; } x0; struct { double x0; _Bool x1; } x1; } x1; long long x2; } transitionContext;
@property (readonly, nonatomic) _Bool transitioning;
@property (retain, nonatomic) BSUIVibrancyConfiguration *vibrancyConfiguration;
@property (retain, nonatomic) BSUIVibrancyConfiguration *vibrancyConfigurationOverride;
@property (readonly, nonatomic) NSArray *visibleViewsPreferringProminentPresentationAndDismissal;
@property (readonly, nonatomic) int wakeSource;
@property (retain, nonatomic) SBWallpaperAggdLogger *wallpaperAggdLogger;
@property (weak, nonatomic) id <CSWallpaperColorProvider> wallpaperColorProvider;
@property (retain, nonatomic) UIGestureRecognizer *wallpaperGestureRecognizer;
@property (readonly, nonatomic) id <SBSWidgetMetricsProviding> widgetMetricsProvider;
@property (weak, nonatomic) id <CSWidgetURLHandling> widgetURLHandler;

/* instance methods */
- (void);
- (id)__currentDesiredAppearanceWithStartIndex:(unsigned long long *)index targetIndex:(unsigned long long *)index targetAppearance:(id *)appearance targetPresentation:(id *)presentation modalAppearance:(id *)appearance proudLockAppearance:(id *)appearance poseidonAppearance:(id *)appearance;
- (unsigned long long)_accessoryAnimationRestrictions;
- (void)_activateCameraAnimated:(_Bool)animated actions:(id)actions completion:(id /* block */)completion;
- (id)_activeRemoteContentAssertion;
- (id)_activeViewControllers;
- (void)_actuallyUpdateUIForIrisNotPlaying;
- (void)_actuallyUpdateUIForIrisPlaying;
- (void)_actuallyUpdateUIForIrisPlaying:(_Bool)playing;
- (void)_addBackgroundContentOccludingViewsForAppearance:(id)appearance;
- (void)_addBackgroundContentViewControllerForAction:(id)action;
- (void)_addBedtimeGreetingBackgroundView;
- (void)_addOrRemoveBlockedViewIfNecessaryAnimated:(_Bool)animated;
- (void)_addOrRemoveRemoteContentViewIfNecessary;
- (void)_addOrRemoveRemoteContentViewIfNecessaryMaintainingState:(_Bool)state;
- (void)_addOrRemoveResetRestoreViewIfNecessaryAnimated:(_Bool)animated;
- (void)_addOrRemoveThermalTrapViewIfNecessaryAnimated:(_Bool)animated;
- (void)_addRemoteViewControllerForAction:(id)action;
- (void)_addStateCaptureHandlers;
- (void)_addVisiblePageViewController:(id)controller;
- (void)_addWhitePointAnimationForKeyPath:(id)path onLayer:(id)layer toValues:(id)values withDuration:(double)duration dispatchGroup:(id)group;
- (id)_allowedPageViewControllers;
- (void)_animateAccessory:(id)accessory toVisibleAnimated:(_Bool)animated;
- (void)_animateView:(id)view toWhitePointReduced:(_Bool)reduced withDuration:(double)duration withDispatchGroup:(id)group;
- (id)_appearanceForParticipant:(id)participant;
- (id)_averageLockScreenWallpaperColor;
- (id)_batteryCenterInternalBattery;
- (_Bool)_batteryCollection:(id)collection containsDeviceWithIdentifier:(id)identifier;
- (void)_beginAppearanceTransitionForPageViewControllersToVisible:(_Bool)visible animated:(_Bool)animated;
- (id)_behaviorForParticipant:(id)participant;
- (void)_calculateAppearanceForCurrentOrientation;
- (_Bool)_canPresentSwipeDismissableModal;
- (_Bool)_canShowEmbeddedRemoteContent;
- (_Bool)_canShowWhileLocked;
- (id)_chargingInfo;
- (void)_cleanupPosterSwitcherPresentationForCompleted:(_Bool)completed withActivatingTouches:(id)touches;
- (void)_cleanupStaleRemoteContentWithCompletion:(id /* block */)completion;
- (void)_clearChargingModalStateIfNecessary;
- (id)_coachingStringToUse;
- (void)_complicationSelected:(id)selected;
- (id)_connectedExternalChargers;
- (_Bool)_containsCachedBatteryDeviceWithIdenfifier:(id)idenfifier;
- (id)_createFakeStatusBar;
- (void)_createStatusBarBackgroundViewIfNeeded;
- (id)_customLockScreenActionContext;
- (double)_dateTimeAlphaForFade;
- (double)_dateTimeInsetXForPage:(id)page;
- (unsigned long long)_dateTimeLayoutForPage:(id)page;
- (double)_dateViewAlphaForCurrentWakeState;
- (void)_dismissAccessoryViewController:(id)controller animated:(_Bool)animated;
- (void)_dismissInlineContentOnSignificantScroll;
- (void)_dismissModalViewController:(id)controller animated:(_Bool)animated completion:(id /* block */)completion;
- (void)_dismissModalViewControllersWithIdentifier:(id)identifier animated:(_Bool)animated completion:(id /* block */)completion;
- (void)_dismissPosterSwitcherViewController;
- (void)_dismissRemoteViewControllerForReason:(long long)reason;
- (void)_dismissRemoteViewControllerForReason:(long long)reason completion:(id /* block */)completion;
- (void)_dismissToMainPageFromPageViewController:(id)controller;
- (void)_displayDidDisappearImplementation;
- (void)_displayWillAppearImplementation;
- (void)_displayWillDisappearImplementation;
- (void)_displayWillTurnOnWhileOnCoverSheet:(id)sheet;
- (id)_eligiblePageViewControllers;
- (void)_endAppearanceTransitionForPageViewControllersToVisible:(_Bool)visible;
- (id)_fakeStatusBarSettings;
- (id)_filterValuesForWhitePointReduced:(_Bool)reduced lighterReduction:(_Bool)reduction;
- (void)_finishFadeInAnimationForPowerSource:(int)source connectedToPower:(_Bool)power screenOn:(_Bool)on;
- (id)_fullscreeNotificationViewControllerMatchingNotificationRequest:(id)request;
- (_Bool)_gestureRecognizer:(id)recognizer isLocatedOverHorizontalContentRegionInViewController:(id)controller;
- (void)_handleAddedAction;
- (void)_handleDismissalForAccessoryViewController:(id)controller animated:(_Bool)animated;
- (_Bool)_handleEvent:(id)event;
- (_Bool)_handleEventType:(long long)type;
- (void)_handlePosterSwitcherActivation:(id)activation;
- (void)_handleQuickNoteLaunch:(id)launch;
- (id)_hostedRemoteContentViewController;
- (unsigned long long)_indexOfCameraPage;
- (unsigned long long)_indexOfMainPage;
- (unsigned long long)_indexOfPageViewControllerForRole:(id)role;
- (unsigned long long)_indexOfTodayPage;
- (void)_invalidateStatusBarAssertions;
- (_Bool)_isAccessoryAnimationAllowedForAccessory:(id)accessory;
- (_Bool)_isComplicationContainerVisible;
- (_Bool)_isFakeStatusBarEnabled;
- (_Bool)_isKnownTransitionConflictFrom:(id)from to:(id)to;
- (_Bool)_isMainPageShowing;
- (_Bool)_isPageContentHidden;
- (_Bool)_isPresentingDismissableRemoteContent;
- (_Bool)_isPresentingModalRemoteContent;
- (_Bool)_isPresentingModalViewControllerWithIdentifier:(id)identifier;
- (_Bool)_isPresentingPosterSwitcher;
- (_Bool)_isRemoteContentPresentedInUnlockMode;
- (_Bool)_isShowingChargingModal;
- (_Bool)_isShowingInlineContent;
- (_Bool)_isShowingNonStaticAccessoryBlockingUI;
- (_Bool)_isSlideableContentOffsetOnscreen:(struct CGPoint { double x0; double x1; })onscreen;
- (_Bool)_isSlideableContentOnscreen;
- (_Bool)_isSourceForHorizontalScrolling:(id)scrolling;
- (_Bool)_isTodayViewOverlayShowing;
- (_Bool)_isWakeAnimationInProgress;
- (void)_liftToWakeGestureDetected;
- (double)_listInsetXForPage:(id)page;
- (void)_listenForDisplayLayoutChanges:(_Bool)changes;
- (void)_loadViewsForRestrictedPagesIfPossible;
- (id)_lockOutController;
- (double)_minDateListSpacingForPage:(id)page;
- (_Bool)_overSlidingControlForLocation:(struct CGPoint { double x0; double x1; })location inView:(id)view;
- (id)_overrideDate;
- (void)_overrideNotificationDisplayStyleForInlineContent;
- (void)_overrideNotificationDisplayStyleWithRemotePreference:(long long)preference;
- (unsigned long long)_pageCapabilities;
- (id)_pageForScrollPercent:(double)percent;
- (long long)_passcodePresentationMode;
- (id)_passcodeViewController;
- (void)_performLocalAppearanceUpdatesWithReason:(id)reason updates:(id /* block */)updates;
- (void)_powerStatusChangedToConnectedState:(_Bool)state;
- (void)_preferredContentSizeDidChange;
- (void)_prepareForPosterSwitcherPresentation;
- (void)_prepareForViewWillAppearIfNecessary;
- (void)_presentInlineViewController:(id)controller;
- (void)_presentModalViewController:(id)controller animated:(_Bool)animated completion:(id /* block */)completion;
- (void)_presentModalViewController:(id)controller shouldDismissOverlays:(_Bool)overlays animated:(_Bool)animated completion:(id /* block */)completion;
- (id)_presentationForParticipant:(id)participant;
- (id)_presentedModalViewControllerWithIdentifier:(id)identifier;
- (_Bool)_quickActionsSupported;
- (void)_removeAllowedPageViewController:(id)controller;
- (void)_removeBackgroundContentOccludingViewsForAppearance:(id)appearance;
- (void)_removeBackgroundContentViewController;
- (void)_removeBedtimeGreetingBackgroundViewAnimated:(_Bool)animated;
- (void)_removeReduceWhitePointAnimationForKeyPath:(id)path onLayer:(id)layer;
- (_Bool)_removeRemoteViewControllerForInvalidatedSession:(id)session completion:(id /* block */)completion;
- (id)_screenWakeAnimationController;
- (void)_scrollPanGestureBegan:(id)began;
- (void)_scrollPanGestureChanged:(id)changed;
- (void)_scrollPanGestureEnded:(id)ended;
- (void)_sendAuthenticationChangedEvent;
- (void)_setAllowedPageViewControllers:(id)controllers;
- (void)_setAppearanceForLandscape:(_Bool)landscape;
- (void)_setDidDismissSinceScreenOn:(_Bool)on;
- (void)_setDismissed:(_Bool)dismissed;
- (void)_setFakeStatusBarEnabled:(_Bool)enabled;
- (void)_setHasContentAboveCoverSheet:(_Bool)sheet;
- (void)_setLockOrientationWhileTransitioning:(_Bool)transitioning;
- (void)_setLockOutController:(id)controller;
- (void)_setMainPageContentViewController:(id)controller;
- (void)_setModalPresentationControllerVisibility:(_Bool)visibility;
- (void)_setModalPresentationControllerVisibility:(_Bool)visibility cancelTouches:(_Bool)touches;
- (void)_setPageViewControllers:(id)controllers;
- (void)_setScreenWakeAnimationController:(id)controller;
- (void)_setupBackgroundContentGestureRecognizer;
- (void)_setupComplicationSelectionGestureRecognizer;
- (void)_setupPosterSwitcherGestureRecognizer;
- (void)_setupQuickNoteGestureRecognizer;
- (void)_setupSearchGesture;
- (void)_setupWallpaperGesture;
- (_Bool)_shouldLoadComplications;
- (_Bool)_shouldReduceWhitePoint;
- (_Bool)_shouldReduceWhitePointForAppearance:(id)appearance;
- (_Bool)_shouldSetUpWallpaperGesture;
- (_Bool)_shouldUpdateActiveAppearanceForReason:(id)reason;
- (void)_showChargingSubtitleWithTimeout:(double)timeout;
- (_Bool)_showingAccessoryView;
- (struct CGPoint { double x0; double x1; })_slideableContentOffset;
- (void)_startFadeInAnimationForSource:(long long)source;
- (double)_timeLabelScrollPercentForDateTimeLayout:(unsigned long long)layout;
- (void)_transitionAccessoryChargingViewToVisible:(_Bool)visible;
- (void)_transitionAccessoryViewToVisible:(_Bool)visible accessory:(id)accessory animated:(_Bool)animated;
- (void)_transitionChargingDateSubtitleToVisible:(_Bool)visible animated:(_Bool)animated force:(_Bool)force;
- (void)_transitionChargingViewToVisible:(_Bool)visible showBattery:(_Bool)battery animated:(_Bool)animated;
- (void)_transitionChargingViewToVisible:(_Bool)visible suppressedByPack:(_Bool)pack showBattery:(_Bool)battery animated:(_Bool)animated;
- (_Bool)_transitionPrototypeChargingViewToVisible:(_Bool)visible animated:(_Bool)animated;
- (void)_transitionTimerViewToVisible:(_Bool)visible animated:(_Bool)animated;
- (void)_updateAccessibilityContentSizesIfNeeded;
- (void)_updateAccessoryAnimationPresenting:(_Bool)presenting userInteractionDisabled:(_Bool)disabled;
- (void)_updateActiveAppearanceForReason:(id)reason;
- (void)_updateActiveBehaviorsForReason:(id)reason;
- (void)_updateActiveBehaviorsForReason:(id)reason updatingAppearanceIfNeeded:(_Bool)needed;
- (void)_updateAppearance:(id)appearance forComponentType:(long long)type shouldHide:(_Bool)hide;
- (void)_updateAppearanceForAODTransitionToInactive:(_Bool)inactive;
- (void)_updateBackground;
- (void)_updateBackgroundContentView;
- (void)_updateCoachingString;
- (void)_updateCoachingStringWithTimeout:(double)timeout;
- (void)_updateComplicationsContainerView;
- (void)_updateContent;
- (void)_updateControlCenterGrabber;
- (void)_updateDateSubtitleAppearanceForBattery:(_Bool)battery animated:(_Bool)animated chargingVisible:(_Bool)visible;
- (void)_updateDateTimeView;
- (void)_updateFixedFooterView;
- (void)_updateForegroundView;
- (void)_updateHomeAffordance;
- (void)_updateIdleTimerBehavior;
- (void)_updateIdleTimerForTransitionProgress:(double)progress;
- (void)_updateLegibilitySettings;
- (void)_updateLocalAppearanceForPresentation;
- (void)_updateLocalAppearanceForRequester:(id)requester animationSettings:(id)settings actions:(id /* block */)actions completion:(id /* block */)completion;
- (void)_updateModalContent;
- (void)_updateModalPresentationControllerVisibility;
- (void)_updateNotificationClearingTriggerForEvent:(id)event;
- (void)_updateOverrideDateIfNeeded;
- (void)_updatePageContent;
- (void)_updatePoseidon;
- (void)_updatePosterSwitcherBackgroundView;
- (void)_updatePosterSwitcherComplicationRowHidden;
- (void)_updatePosterSwitcherPresentationWithProgress:(double)progress;
- (void)_updateProudLockView;
- (void)_updateProudLockViewUpdateSuspension;
- (void)_updateQuickActions;
- (void)_updateRemoteInlineContentView;
- (void)_updateRestrictedBehavior;
- (void)_updateScrollingBehavior;
- (void)_updateSensitiveUIModuleVisibility;
- (void)_updateStatusBar;
- (void)_updateStatusBarBackground;
- (void)_updateStatusBarGradient;
- (void)_updateTintingView;
- (void)_updateUIForPlaying:(_Bool)playing immediately:(_Bool)immediately;
- (void)_updateVibrancy;
- (void)_updateVisibilityForPageViewControllersWithVisiblePageViewController:(id)controller;
- (void)_updateWallpaper;
- (void)_updateWallpaperEffectView;
- (void)_updateWallpaperFloatingLayerContainerView;
- (void)_updateWhitePoint;
- (_Bool)_wallpaperGestureShouldRequireUserPresence;
- (id)_whitePointReductionFilterFromValues:(id)values;
- (id)_whitePointValues;
- (id)_whitePointValuesForAppearance:(id)appearance;
- (id)_windowsFromViewControllers:(id)controllers;
- (_Bool)_wouldUpdateActiveAppearance;
- (void)accessoryAnimationStatusChanged:(_Bool)changed;
- (void)accessoryAttached:(id)attached;
- (id)accessoryAttachmentObserver;
- (void)accessoryDetached:(id)detached;
- (void)actionManager:(id)manager addedAction:(id)action;
- (void)actionManager:(id)manager removedAction:(id)action;
- (void)activateCameraViewAnimated:(_Bool)animated sendingActions:(id)actions completion:(id /* block */)completion;
- (void)activateMainPageWithCompletion:(id /* block */)completion;
- (void)activatePage:(unsigned long long)page animated:(_Bool)animated withCompletion:(id /* block */)completion;
- (void)activateTodayViewWithCompletion:(id /* block */)completion;
- (id)activeAppearance;
- (id)activeBehavior;
- (id)activePresentation;
- (id)activityCenter;
- (void)activityItemsMayHaveChanged;
- (id)activityPickerViewControllerTransitionContainerView:(id)view;
- (void)addApplicationHoster:(id)hoster;
- (void)addCoverSheetObserver:(id)observer;
- (void)addRemoteContentInlineProvidingManager:(id)manager;
- (void)animationDidStop:(id)stop finished:(_Bool)finished;
- (id)applicationLauncher;
- (_Bool)attachedAccessoriesContainsAccessoryType:(long long)type;
- (void)attemptPhoneUnlockWithWatch;
- (void)backgroundContentActionManager:(id)manager addedAction:(id)action;
- (void)backgroundContentActionManager:(id)manager removedAction:(id)action;
- (double)backlightLevel;
- (long long)backlightLuminance;
- (double)bottomContentInset;
- (id)cameraPrewarmer;
- (_Bool)canBeDeactivatedForUIUnlockFromSource:(int)source;
- (_Bool)canHostAnApp;
- (void)cancelTransition;
- (void)cleanupInterstitialPresentationToPresented:(_Bool)presented inPlace:(_Bool)place;
- (void)cleanupRubberBandTransition;
- (void)combinedListViewController:(id)controller didChangeVisibleBreakthroughContent:(_Bool)content;
- (void)completePhoneAutoUnlockWithNotification:(_Bool)notification;
- (id)complicationContainerViewController;
- (void)conformsToCSAppearanceProviding;
- (void)conformsToCSBehaviorProviding;
- (void)conformsToCSCoverSheetViewControlling;
- (void)conformsToCSCoverSheetViewPresenting;
- (void)conformsToCSEventHandling;
- (void)connectedDevicesDidChange:(id)change;
- (_Bool)containsCenteredDateTimeLayout;
- (_Bool)contentOccludesBackground;
- (void)contentRequestCancellingGesture;
- (_Bool)controller:(id)controller shouldAllowPanScrollingWithSystemGestureRecognizer:(id)recognizer;
- (void)controllerWillCancelHorizontalScrolling:(id)scrolling;
- (id)coverSheetContext;
- (id)coverSheetIdentifier;
- (void)coverSheetLegibilityProviderDidUpdate:(id)update;
- (void)coverSheetNotificationClearingTriggerDidFire:(id)fire;
- (id)coverSheetSpotlightPresenter;
- (id)coverSheetView;
- (id)createHomeButtonShowPasscodeRecognizerForHomeButtonPress;
- (id)createHomeButtonSuppressAfterUnlockRecognizerForUnlockSource:(int)source;
- (id)currentTransitionSource;
- (double)dateBaselineToComplicationY;
- (double)dateTimeMostExtremeLeadingX;
- (double)dateTimeMostExtremeTrailingX;
- (double)dateTimeSubtitleMaximumWidth;
- (id)dateView;
- (id)dateViewController;
- (void)deactivateTodayViewWithCompletion:(id /* block */)completion;
- (void)dealloc;
- (id)delegate;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (void)didAddNewActivityItemSceneHostEnvironment;
- (_Bool)didDetectBottomFaceOcclusionsSinceScreenOn;
- (_Bool)didDetectFaceOcclusionsSinceScreenOn;
- (_Bool)didDetectFaceRequirementsForPAU;
- (_Bool)didDismissSinceScreenOn;
- (void)didPostNotificationRequest:(id)request;
- (void)dismissHomeScreenOverlay;
- (void)dismissModalViewController:(id)controller animated:(_Bool)animated completion:(id /* block */)completion;
- (_Bool)dismissNotificationInLongLookAnimated:(_Bool)animated;
- (void)dismissOverlaysAnimated:(_Bool)animated;
- (_Bool)dismissed;
- (id)dispatcher;
- (long long)effectiveInterfaceOrientation;
- (long long)effectiveInterfaceOrientationOverride;
- (id)effectiveVibrancyConfiguration;
- (id)emergencyCaller;
- (void)externalAppearanceProviderBehaviorChanged:(id)changed;
- (void)externalBehaviorProviderBehaviorChanged:(id)changed;
- (void)externalLockProviderStateChanged:(id)changed;
- (_Bool)externalLockProvidersRequireUnlock;
- (_Bool)externalLockProvidersShowPasscode;
- (id)externalPresentation;
- (void)externalPresentationProviderPresentationChanged:(id)changed;
- (id)fakeStatusBar;
- (void)fillRestToOpenWithDuration:(double)duration;
- (void)finishUIUnlockFromSource:(int)source;
- (double)focusActivityHeight;
- (_Bool)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)recognizer;
- (_Bool)gestureRecognizer:(id)recognizer shouldRequireFailureOfGestureRecognizer:(id)recognizer;
- (_Bool)gestureRecognizerShouldBegin:(id)begin;
- (void)handleAction:(id)action fromSender:(id)sender;
- (void)handleBiometricEvent:(unsigned long long)event;
- (_Bool)handleHeadsetButtonPress:(_Bool)press;
- (_Bool)handleHomeButtonDoublePress;
- (_Bool)handleHomeButtonLongPress;
- (_Bool)handleHomeButtonPress;
- (_Bool)handleLockButtonPress;
- (void)handleReachabilityAnimationDidEnd;
- (void)handleReachabilityAnimationWillBegin;
- (_Bool)handleVoiceCommandButtonPress;
- (_Bool)handleVolumeDownButtonPress;
- (_Bool)handleVolumeUpButtonPress;
- (_Bool)hasContentAboveCoverSheet;
- (_Bool)hasPresentedForInterstitialTransitionSource;
- (_Bool)hasVisibleContentToReveal;
- (id)hostedAppSceneHandle;
- (id)hostedAppSceneHandles;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)orientation;
- (id)idleTimerController;
- (void)idleTimerDidChange;
- (void)idleTimerDidExpire;
- (void)idleTimerDidRefresh;
- (void)idleTimerDidWarn;
- (void)idleTimerWillRefresh;
- (id)initWithPageViewControllers:(id)controllers mainPageContentViewController:(id)controller context:(id)context;
- (double)initialOverlayPresentationProgress;
- (id)inlineComplicationContainerViewController;
- (_Bool)interceptDismissalGestureForOverlayController:(id)controller;
- (_Bool)interpretsTouchLocationAsContentInListRestrictedRect:(struct CGPoint { double x0; double x1; })rect;
- (id)interstitialTransitionSource;
- (void)invalidateLockScreenActionContext;
- (id)irisBehavior;
- (_Bool)irisPlayerIsInteracting;
- (id)irisWallpaperPlayer;
- (void)irisWallpaperPlayer:(id)player didReplaceGestureRecognizer:(id)recognizer withGestureRecognizer:(id)recognizer;
- (void)irisWallpaperPlayerIsInteractingDidChange:(id)change;
- (void)irisWallpaperPlayerPlaybackStateDidChange:(id)change;
- (_Bool)isAccessoryAnimationPresenting;
- (_Bool)isAlternateDateEnabled;
- (_Bool)isAuthenticated;
- (_Bool)isHostingAnApp;
- (_Bool)isInScreenOffMode;
- (_Bool)isInlinePasscodeLockVisible;
- (_Bool)isLockScreenShowingDefaultContent;
- (_Bool)isLockScreenShowingDefaultContentExceptControlCenter;
- (_Bool)isMainPageVisible;
- (_Bool)isNotificationContentExtensionVisible:(id)visible;
- (_Bool)isPasscodeLockVisible;
- (_Bool)isPresentingNotificationInLongLook;
- (_Bool)isRestToOpenAvailable;
- (_Bool)isShowingMediaControls;
- (_Bool)isShowingModalView;
- (_Bool)isShowingTodayView;
- (_Bool)isTransitioning;
- (_Bool)isTransitioningInteractively;
- (_Bool)isUnlockDisabled;
- (void)jiggleLockIcon;
- (id)landscapeInlineComplicationContainerViewController;
- (unsigned long long)lastSettledPageIndex;
- (id)layoutStrategy;
- (id)legacyWallpaperWakeAnimator;
- (id)legibilityProvider;
- (double)listMinY;
- (void)loadView;
- (id)localAppearance;
- (id)localBehavior;
- (_Bool)lockOrientationWhileTransitioning;
- (id)lockScreenActionContext;
- (id)mainPageContentViewController;
- (id)mainPagePresentationViewController;
- (id)modalPresentationController;
- (void)noteDeviceBlockedStatusUpdated;
- (void)noteResetRestoreStateUpdated;
- (void)noteWillPresentForUserGesture;
- (id)notificationDestination;
- (void)notificationsLoadedForSectionIdentifier:(id)identifier;
- (id)orientationUpdateController;
- (id)overlayController;
- (void)overlayController:(id)controller didChangePresentationProgress:(double)progress newPresentationProgress:(double)progress fromLeading:(_Bool)leading;
- (void)overlayController:(id)controller visibilityDidChange:(_Bool)change;
- (void)overlayControllerDidBeginChangingPresentationProgress:(id)progress;
- (id)overlayControllerIfExists;
- (void)overlayControllerRequestsDismissal:(id)dismissal;
- (id)pageViewControllerAtIndex:(unsigned long long)index;
- (id)pageViewControllers;
- (_Bool)partiallyOnScreen;
- (long long)participantState;
- (void)passcodeViewController:(id)controller didCompletePasscodeEntry:(_Bool)entry;
- (void)passcodeViewControllerDidBeginPasscodeEntry:(id)entry;
- (void)passcodeViewControllerDidCancelPasscodeEntry:(id)entry;
- (_Bool)passcodeViewControllerShouldHideStatusBar:(id)bar;
- (id)pendingModalViewControllers;
- (void)phoneUnlockWithWatchControllerAttemptFailed:(id)failed withError:(id)error;
- (void)phoneUnlockWithWatchControllerAttemptSucceeded:(id)succeeded;
- (_Bool)phoneUnlockWithWatchControllerShowRawErrorCodes:(id)codes;
- (_Bool)phoneUnlockWithWatchEnabled;
- (void)postNotificationRequest:(id)request;
- (id)posterSwitcherActivationManager;
- (void)posterSwitcherActivationManager:(id)manager didChangeToCoachingText:(id)text;
- (id)posterSwitcherPresentationStatus;
- (id)posterSwitcherTransitionSource;
- (id)posterSwitcherViewController;
- (id)powerChangeObserver;
- (long long)preferredInterfaceOrientationForPresentation;
- (void)prepareForInterstitialPresentation;
- (void)prepareForUILock;
- (void)prepareForUIUnlock;
- (void)prepareRubberBandTransition;
- (void)presentModalViewController:(id)controller animated:(_Bool)animated completion:(id /* block */)completion;
- (void)presentModalViewController:(id)controller fromRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect inView:(id)view animated:(_Bool)animated;
- (void)presentModalViewController:(id)controller withTransition:(int)transition;
- (void)presentOrDismissCoverSheetSpotlightAnimated:(_Bool)animated;
- (long long)presentationAltitude;
- (id)presentationCoordinateSpace;
- (unsigned int)presentationFrameRateRangeReason;
- (struct CAFrameRateRange { float x0; float x1; float x2; })presentationPreferredFrameRateRange;
- (long long)presentationPriority;
- (id)presentationRegions;
- (long long)presentationStyle;
- (long long)presentationTransition;
- (long long)presentationType;
- (void)presentationViewController:(id)controller didTransitionViewController:(id)controller toPresented:(_Bool)presented;
- (id)presenter;
- (_Bool)preventsLaunchFromWidgetWithAction:(id)action;
- (id)previousAppearance;
- (double)prominentBaselineToListY;
- (void)proudLockDidChangeToCoachingText:(id)text;
- (_Bool)proudLockViewControllerIsCoverSheetVisible;
- (void)publisher:(id)publisher didUpdateLayout:(id)layout withTransition:(id)transition;
- (void)registerExternalAppearanceProvider:(id)provider;
- (void)registerExternalBehaviorProvider:(id)provider;
- (void)registerExternalEventHandler:(id)handler;
- (void)registerExternalLockProvider:(id)provider;
- (void)registerExternalPresentationProvider:(id)provider;
- (double)remoteContentComplicationHeightInset;
- (void)remoteContentDidUpdateStyle;
- (void)remoteContentSession:(id)session didInvalidateWithError:(id)error;
- (_Bool)remoteContentSession:(id)session dismissWithReason:(long long)reason completion:(id /* block */)completion;
- (_Bool)remoteContentSession:(id)session presentViewController:(id)controller;
- (void)removeApplicationHoster:(id)hoster;
- (void)removeCoverSheetObserver:(id)observer;
- (void)removeRemoteContentInlineProvidingManager:(id)manager;
- (void)resetMainPageContentOffset;
- (void)resetRestToOpen;
- (id)sceneHostEnvironmentEntriesForBacklightSession;
- (void)scrollPanGestureDidUpdate:(id)update;
- (void)scrollablePageViewController:(id)controller scrollViewDidScroll:(id)scroll;
- (void)scrollablePageViewController:(id)controller scrollViewWillBeginDragging:(id)dragging;
- (void)scrollablePageViewController:(id)controller scrollViewWillEndDragging:(id)dragging;
- (id)searchGesture;
- (void)searchGesture:(id)gesture changedPercentComplete:(double)complete;
- (void)searchGesture:(id)gesture completedShowing:(_Bool)showing;
- (void)searchGesture:(id)gesture endedGesture:(_Bool)gesture;
- (void)searchGesture:(id)gesture startedShowing:(_Bool)showing;
- (_Bool)searchGestureShouldRecognize:(id)recognize;
- (_Bool)sendAppearanceTransitionForChildViewControllers;
- (void)setAccessoryAttachmentObserver:(id)observer;
- (void)setActiveAppearance:(id)appearance;
- (void)setActiveBehavior:(id)behavior;
- (void)setActivePresentation:(id)presentation;
- (void)setActivityCenter:(id)center;
- (void)setAlternateDateEnabled:(_Bool)enabled;
- (void)setApplicationLauncher:(id)launcher;
- (void)setAuthenticated:(_Bool)authenticated;
- (void)setBacklightLevel:(double)level;
- (void)setCameraPrewarmer:(id)prewarmer;
- (void)setComplicationContainerViewController:(id)controller;
- (void)setCoverSheetIsVisible:(_Bool)visible;
- (void)setCoverSheetSpotlightPresenter:(id)presenter;
- (void)setCurrentTransitionSource:(id)source;
- (void)setCustomLockScreenActionContext:(id)context;
- (void)setDateViewController:(id)controller;
- (void)setDelegate:(id)delegate;
- (void)setDispatcher:(id)dispatcher;
- (void)setEffectiveInterfaceOrientationOverride:(long long)override;
- (void)setEffectiveVibrancyConfiguration:(id)configuration;
- (void)setEmergencyCaller:(id)caller;
- (void)setFakeStatusBar:(id)bar;
- (void)setHasPresentedForInterstitialTransitionSource:(_Bool)source;
- (void)setIdleTimerController:(id)controller;
- (void)setInScreenOffMode:(_Bool)mode;
- (void)setInScreenOffMode:(_Bool)mode forAutoUnlock:(_Bool)unlock fromUnlockSource:(int)source;
- (void)setInitialOverlayPresentationProgress:(double)progress;
- (void)setInlineComplicationContainerViewController:(id)controller;
- (void)setInterstitialTransitionSource:(id)source;
- (void)setIrisBehavior:(id)behavior;
- (void)setIrisPlayerIsInteracting:(_Bool)interacting;
- (void)setIrisWallpaperPlayer:(id)player;
- (void)setLandscapeInlineComplicationContainerViewController:(id)controller;
- (void)setLastSettledPageIndex:(unsigned long long)index;
- (void)setLayoutStrategy:(id)strategy;
- (void)setLegibilityProvider:(id)provider;
- (void)setLegibilitySettings:(id)settings;
- (void)setLocalAppearance:(id)appearance;
- (void)setLocalBehavior:(id)behavior;
- (void)setModalPresentationController:(id)controller;
- (void)setOrientationUpdateController:(id)controller;
- (void)setOverlayController:(id)controller;
- (void)setPartiallyOnScreen:(_Bool)screen;
- (void)setPasscodeLockVisible:(_Bool)visible animated:(_Bool)animated;
- (void)setPasscodeLockVisible:(_Bool)visible animated:(_Bool)animated completion:(id /* block */)completion;
- (void)setPasscodeLockVisible:(_Bool)visible animated:(_Bool)animated forceBiometricPresentation:(_Bool)presentation completion:(id /* block */)completion;
- (void)setPendingModalViewControllers:(id)controllers;
- (void)setPosterSwitcherActivationManager:(id)manager;
- (void)setPosterSwitcherTransitionSource:(id)source;
- (void)setPosterSwitcherViewController:(id)controller;
- (void)setPowerChangeObserver:(id)observer;
- (void)setPresenter:(id)presenter;
- (void)setPreviousAppearance:(id)appearance;
- (void)setRestrictsTouchesForRemoteView:(_Bool)view;
- (void)setSearchGesture:(id)gesture;
- (void)setShouldTransitionIrisWallpaperToStillWhenPlaybackFinishes:(_Bool)finishes;
- (void)setShowingMediaControls:(_Bool)controls;
- (void)setSpotlightInteractiveGestureTransaction:(id)transaction;
- (void)setStatusBarBackgroundView:(id)view;
- (void)setSuspendWallpaperAnimationAssertion:(id)assertion;
- (void)setTimerViewController:(id)controller;
- (void)setVibrancyConfiguration:(id)configuration;
- (void)setVibrancyConfigurationOverride:(id)override;
- (void)setWallpaperAggdLogger:(id)logger;
- (void)setWallpaperColorProvider:(id)provider;
- (void)setWallpaperGestureRecognizer:(id)recognizer;
- (void)setWidgetURLHandler:(id)urlhandler;
- (void)settings:(id)settings changedValueForKey:(id)key;
- (_Bool)shouldActivateRemoteContentSession:(id)session;
- (_Bool)shouldAutoUnlockForSource:(int)source;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)shouldAutorotate;
- (_Bool)shouldCompletePhoneAutoUnlockWithNotification;
- (_Bool)shouldDisableALS;
- (_Bool)shouldModifyPageScrolling;
- (_Bool)shouldPresentOrDismissCoverSheetSpotlight;
- (_Bool)shouldShowLockStatusBarTime;
- (_Bool)shouldTransitionIrisWallpaperToStillWhenPlaybackFinishes;
- (_Bool)shouldUnlockUIOnKeyDownEvent;
- (id)spotlightInteractiveGestureTransaction;
- (void)spotlightPresenter:(id)presenter dismissDismissableModalViewController:(id)controller animated:(_Bool)animated completion:(id /* block */)completion;
- (void)spotlightPresenter:(id)presenter presentDismissableModalViewController:(id)controller completion:(id /* block */)completion;
- (void)spotlightPresenterAddContentView:(id)view;
- (_Bool)spotlightPresenterAllowsPullToSearch:(id)search;
- (void)spotlightPresenterRemoveContentView:(id)view;
- (void)startLockScreenFadeInAnimationForSource:(int)source;
- (void)startRestToOpenCoachingWithCompletion:(id /* block */)completion;
- (id)statusBarBackgroundView;
- (long long)statusBarStyle;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)suppressesBanners;
- (_Bool)suppressesControlCenter;
- (_Bool)suppressesScreenshots;
- (id)suspendWallpaperAnimationAssertion;
- (double)timeLabelBaselineY;
- (double)timeLabelOffsetForScrollPercent:(double)percent;
- (double)timeToSubtitleLabelBaselineDifferenceY;
- (void)timerControllerDidStartTimer:(id)timer;
- (void)timerControllerDidStopTimer:(id)timer;
- (void)timerControllerDidUpdateTimer:(id)timer;
- (id)timerViewController;
- (void)traitCollectionDidChange:(id)change;
- (struct { double x0; struct { struct { double x0; _Bool x1; } x0; struct { double x0; _Bool x1; } x1; } x1; long long x2; })transitionContext;
- (void)transitionSource:(id)source didEndWithContext:(struct { double x0; struct { struct { double x0; _Bool x1; } x0; struct { double x0; _Bool x1; } x1; } x1; long long x2; })context;
- (void)transitionSource:(id)source didUpdateTransitionWithContext:(struct { double x0; struct { struct { double x0; _Bool x1; } x0; struct { double x0; _Bool x1; } x1; } x1; long long x2; })context;
- (void)transitionSource:(id)source willBeginWithType:(long long)type;
- (void)unregisterExternalAppearanceProvider:(id)provider;
- (void)unregisterExternalBehaviorProvider:(id)provider;
- (void)unregisterExternalEventHandler:(id)handler;
- (void)unregisterExternalLockProvider:(id)provider;
- (void)unregisterExternalPresentationProvider:(id)provider;
- (void)updateAppearanceForController:(id)controller;
- (void)updateAppearanceForController:(id)controller withAnimationSettings:(id)settings completion:(id /* block */)completion;
- (void)updateBehaviorForController:(id)controller;
- (void)updateCallToActionForMesaMatchFailure;
- (void)updateFloatingLayerOrdering;
- (void)updateFont:(id)font vibrancyConfiguration:(id)configuration numberingSystem:(id)system;
- (void)updateInterstitialPresentationWithProgress:(double)progress;
- (void)updateLeadingTopButtonFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame trailingTopButtonFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)updateNotificationRequest:(id)request;
- (void)updateNotificationSectionSettings:(id)settings previousSectionSettings:(id)settings;
- (void)updateNotificationSystemSettings:(id)settings previousSystemSettings:(id)settings;
- (void)updateQuickActionsVisibility;
- (void)updateScaleViewWithScale:(double)scale withDuration:(double)duration;
- (void)updateStatusBarForLockScreenComeback;
- (void)updateStatusBarForLockScreenTeardown;
- (_Bool)userPresenceDetectedSinceWake;
- (id)vibrancyConfiguration;
- (id)vibrancyConfigurationOverride;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewDidDisappear:(_Bool)disappear;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })size withTransitionCoordinator:(id)coordinator;
- (id)visiblePageViewController;
- (id)visibleViewsPreferringProminentPresentationAndDismissal;
- (int)wakeSource;
- (id)wallpaperAggdLogger;
- (id)wallpaperColorProvider;
- (id)wallpaperGestureRecognizer;
- (id)widgetMetricsProvider;
- (id)widgetURLHandler;
- (_Bool)willUIUnlockFromSource:(int)source;
- (double)windowedAccessoryInset;
- (void)withdrawNotificationRequest:(id)request;
- (_Bool)wouldHandleButtonEvent:(id)event;

@end

#endif /* CSCoverSheetViewController_h */