//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PBUISnapshotReplicaView_h
#define PBUISnapshotReplicaView_h
@import Foundation;

#include "BSInvalidatable-Protocol.h"
#include "PBUIFakeBlurObserver-Protocol.h"
#include "PBUIFakeBluring-Protocol.h"
#include "PBUIPosterReplicaSnapshotProviding-Protocol.h"
#include "PBUIPosterReplicaView-Protocol.h"
#include "PBUIReplicaDebugView.h"
#include "PBUIReplicaSnapshotSource-Protocol.h"
#include "PBUIWallpaperPositioning-Protocol.h"

@class UIImageView, UIView, _UILegibilitySettings;

@interface PBUISnapshotReplicaView : UIView <PBUIFakeBluring, PBUIPosterReplicaView, PBUIWallpaperPositioning> {
    /* instance variables */
    PBUIReplicaDebugView *_debugView;
    long long _effectiveStyle;
    UIImageView *_imageView;
    _Bool _invalidated;
    _UILegibilitySettings *_legibilitySettings;
    id <PBUIFakeBlurObserver> _observer;
    id <PBUIPosterReplicaSnapshotProviding> _provider;
    id <BSInvalidatable> _providerToken;
    NSString *_reason;
    _Bool _shouldMatchWallpaperPosition;
    id <PBUIReplicaSnapshotSource> _source;
    id <BSInvalidatable> _sourceToken;
    _Bool _subscribed;
    unsigned long long _transformOptions;
    double _zoomScale;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) PBUIReplicaDebugView *debugView;
@property (readonly, copy) NSString *description;
@property (nonatomic) long long effectiveStyle;
@property (nonatomic) _Bool fullscreen;
@property (readonly) unsigned long long hash;
@property (weak, nonatomic) id <PBUIFakeBlurObserver> observer;
@property (weak, nonatomic) id <PBUIPosterReplicaSnapshotProviding> provider;
@property (copy, nonatomic) NSString *reason;
@property (nonatomic) _Bool shouldMatchWallpaperPosition;
@property (readonly, nonatomic) id <PBUIReplicaSnapshotSource> source;
@property (nonatomic) _Bool subscribed;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long transformOptions;
@property (readonly, nonatomic) _Bool valid;
@property (nonatomic) double zoomScale;

/* class methods */
+ (_Bool)automaticallyNotifiesObserversForValid;

/* instance methods */
- (void)dealloc;
- (id)debugView;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (long long)effectiveStyle;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)invalidate;
- (_Bool)isFullscreen;
- (_Bool)isSubscribed;
- (_Bool)isValid;
- (void)layoutSubviews;
- (id)observer;
- (void)offsetWallpaperBy:(struct CGPoint { double x0; double x1; })by;
- (id)provider;
- (id)reason;
- (void)requestStyle:(long long)style;
- (void)setEffectiveStyle:(long long)style;
- (void)setFullscreen:(_Bool)fullscreen;
- (void)setNeedsProviderUpdate;
- (void)setNeedsSourceUpdate;
- (void)setObserver:(id)observer;
- (void)setProvider:(id)provider;
- (void)setReason:(id)reason;
- (void)setShouldMatchWallpaperPosition:(_Bool)position;
- (void)setSubscribed:(_Bool)subscribed;
- (void)setTransformOptions:(unsigned long long)options;
- (void)setZoomScale:(double)scale;
- (_Bool)shouldMatchWallpaperPosition;
- (id)source;
- (unsigned long long)transformOptions;
- (void)willMoveToSuperview:(id)superview;
- (void)willMoveToWindow:(id)window;
- (double)zoomScale;

@end

#endif /* PBUISnapshotReplicaView_h */