//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PBUIFakeBlurView_h
#define PBUIFakeBlurView_h
@import Foundation;

#include "PBUIFakeBlurImageProviding-Protocol.h"
#include "PBUIFakeBlurObserver-Protocol.h"
#include "PBUIFakeBlurViewRegistering-Protocol.h"
#include "PBUIFakeBluring-Protocol.h"
#include "PBUIWallpaperReachabilityObserving-Protocol.h"
#include "PBUIWallpaperView.h"
#include "PBUIWallpaperViewController.h"

@class UIView;
@protocol PBUIWallpaperReachabilityCoordinating;

@interface PBUIFakeBlurView : UIView <PBUIFakeBlurImageProviding, PBUIFakeBluring, PBUIWallpaperReachabilityObserving> {
    /* instance variables */
    long long _effectiveStyle;
    id <PBUIFakeBlurViewRegistering> _fakeBlurRegistry;
    id <PBUIFakeBlurImageProviding> _imageProvider;
    id <PBUIFakeBlurObserver> _observer;
    UIView *_providedImageView;
    id <PBUIWallpaperReachabilityCoordinating> _reachabilityCoordinator;
    long long _requestedStyle;
    _Bool _shouldMatchWallpaperPosition;
    unsigned long long _transformOptions;
    struct CGPoint { double x; double y; } _wallpaperOffset;
    PBUIWallpaperView *_wallpaperView;
    PBUIWallpaperViewController *_wallpaperViewController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, weak, nonatomic) id <PBUIFakeBlurViewRegistering> fakeBlurRegistry;
@property (nonatomic) _Bool fullscreen;
@property (readonly) unsigned long long hash;
@property (readonly, weak, nonatomic) id <PBUIFakeBlurImageProviding> imageProvider;
@property (weak, nonatomic) id <PBUIFakeBlurObserver> observer;
@property (readonly, nonatomic) UIView *providedImageView;
@property (readonly, nonatomic) id <PBUIWallpaperReachabilityCoordinating> reachabilityCoordinator;
@property (nonatomic) _Bool shouldMatchWallpaperPosition;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long transformOptions;
@property (readonly, nonatomic) long long variant;
@property (readonly, weak, nonatomic) PBUIWallpaperViewController *wallpaperViewController;
@property (nonatomic) double zoomScale;

/* class methods */
+ (id)_imageForStyle:(inout long long *)style withSource:(id)source;
+ (id)_imageForStyle:(inout long long *)style withSource:(id)source overrideTraitCollection:(id)collection;
+ (void)_imageForStyle:(long long)style withSource:(id)source overrideTraitCollection:(id)collection result:(id /* block */)result;

/* instance methods */
- (void)dealloc;
- (id)description;
- (void)didMoveToWindow;
- (long long)effectiveStyle;
- (id)fakeBlurRegistry;
- (void)handleReachabilityYOffsetDidChange;
- (id)imageForWallpaperStyle:(inout long long *)style variant:(long long)variant traitCollection:(id)collection;
- (id)imageProvider;
- (id)initWithVariant:(long long)variant imageProvider:(id)provider fakeBlurRegistry:(id)registry wallpaperViewDelegate:(id)delegate transformOptions:(unsigned long long)options reachabilityCoordinator:(id)coordinator;
- (id)initWithVariant:(long long)variant wallpaperViewController:(id)controller transformOptions:(unsigned long long)options reachabilityCoordinator:(id)coordinator;
- (_Bool)isFullscreen;
- (void)layoutSubviews;
- (id)newImageProviderView;
- (id)observer;
- (void)offsetWallpaperBy:(struct CGPoint { double x0; double x1; })by;
- (_Bool)parallaxEnabledForVariant:(long long)variant;
- (double)parallaxFactorForVariant:(long long)variant;
- (id)providedImageView;
- (id)reachabilityCoordinator;
- (void)reconfigureFromProvider;
- (void)reconfigureWithSource:(id)source;
- (void)requestStyle:(long long)style;
- (void)rotateToInterfaceOrientation:(long long)orientation;
- (void)setFullscreen:(_Bool)fullscreen;
- (void)setObserver:(id)observer;
- (void)setShouldMatchWallpaperPosition:(_Bool)position;
- (void)setTransformOptions:(unsigned long long)options;
- (void)setZoomScale:(double)scale;
- (_Bool)shouldMatchWallpaperPosition;
- (void)traitCollectionDidChange:(id)change;
- (unsigned long long)transformOptions;
- (void)updateImageFromProviderForWallpaperMode:(long long)mode;
- (_Bool)updateImageProviderView:(id)view withImage:(id)image;
- (void)updateImageWithSource:(id)source;
- (long long)variant;
- (id)wallpaperViewController;
- (void)willMoveToWindow:(id)window;
- (double)zoomFactorForVariant:(long long)variant;
- (double)zoomScale;

@end

#endif /* PBUIFakeBlurView_h */