//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PBUIPortalReplicaEffectView_h
#define PBUIPortalReplicaEffectView_h
@import Foundation;

#include "PBUIFakeBlurObserver-Protocol.h"
#include "PBUIFakeBluring-Protocol.h"
#include "PBUIPortalReplicaView.h"

@class MTMaterialView, _UIBackdropView;

@interface PBUIPortalReplicaEffectView : PBUIPortalReplicaView <PBUIFakeBluring> {
    /* instance variables */
    _UIBackdropView *_effectView;
    MTMaterialView *_materialView;
    id <PBUIFakeBlurObserver> _observer;
    long long _style;
    unsigned long long _transformOptions;
    double _zoomScale;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) double effectWeight;
@property (nonatomic) _Bool fullscreen;
@property (readonly) unsigned long long hash;
@property (weak, nonatomic) id <PBUIFakeBlurObserver> observer;
@property (nonatomic) _Bool shouldMatchWallpaperPosition;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long transformOptions;
@property (nonatomic) double zoomScale;

/* instance methods */
- (double)effectWeight;
- (long long)effectiveStyle;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (_Bool)isEffectView;
- (_Bool)isFullscreen;
- (id)observer;
- (void)offsetWallpaperBy:(struct CGPoint { double x0; double x1; })by;
- (void)requestStyle:(long long)style;
- (void)setEffectWeight:(double)weight;
- (void)setFullscreen:(_Bool)fullscreen;
- (void)setNeedsSourceUpdate;
- (void)setObserver:(id)observer;
- (void)setTransformOptions:(unsigned long long)options;
- (void)setZoomScale:(double)scale;
- (unsigned long long)transformOptions;
- (double)zoomScale;

@end

#endif /* PBUIPortalReplicaEffectView_h */