//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PBUIWallpaperConfigurationManager_h
#define PBUIWallpaperConfigurationManager_h
#import <Foundation/Foundation.h>
#import "PBUIWallpaperConfiguration.h"

@class PBUIMagnifyMode;
@protocol BSDescriptionProviding;
@protocol PBUIProceduralWallpaperProvider;
@protocol PBUIWallpaperConfigurationManagerDelegate;

@interface PBUIWallpaperConfigurationManager : NSObject {
    /* instance variables */
    unsigned long long _batchChangeCount;
    long long _batchNotifyVariants;
    _Bool _cachedVariantsShareWallpaperConfiguration;
    _Bool _cachedVariantsShareWallpaperConfigurationValid;
    NSArray *_dataStores;
    id <PBUIWallpaperConfigurationManagerDelegate> _delegate;
    _Bool _enableWallpaperDimming;
    int _externalNotificationToken;
    PBUIMagnifyMode *_magnifyMode;
    id <PBUIProceduralWallpaperProvider> _proceduralWallpaperProvider;
    NSMutableDictionary *_wallpaperImageCache;
    long long _wallpaperMode;
    double _wallpaperScale;
    CGSize _wallpaperSize;
    long long _wallpaperSizeType;
}

@property (nonatomic) _Bool cachedVariantsShareWallpaperConfiguration;
@property (nonatomic) _Bool cachedVariantsShareWallpaperConfigurationValid;
@property (readonly, copy, nonatomic) NSArray *dataStores;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <PBUIWallpaperConfigurationManagerDelegate> delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) _Bool enableWallpaperDimming;
@property (readonly) unsigned long long hash;
@property (readonly, copy, nonatomic) PBUIWallpaperConfiguration *homeScreenWallpaperConfiguration;
@property (readonly, copy, nonatomic) PBUIWallpaperConfiguration *lockScreenWallpaperConfiguration;
@property (retain, nonatomic) PBUIMagnifyMode *magnifyMode;
@property (readonly, nonatomic) unsigned long long numberOfCachedStaticImages;
@property (readonly, nonatomic) long long parallaxDeviceType;
@property (weak, nonatomic) id <PBUIProceduralWallpaperProvider> proceduralWallpaperProvider;
@property (readonly) Class superclass;
@property (readonly, nonatomic) _Bool variantsShareWallpaperConfiguration;
@property (nonatomic) long long wallpaperMode;
@property (readonly, nonatomic) double wallpaperScale;
@property (readonly, nonatomic) CGSize wallpaperSize;
@property (readonly, nonatomic) CGSize wallpaperSizeIncludingParallaxOverhang;
@property (readonly, nonatomic) long long wallpaperSizeType;

/* class methods */
+ (void)initialize;

/* instance methods */
- (CGAffineTransform)_naturalPreferredTransform:(CGAffineTransform)transform forNaturalSize:(CGSize)size;
- (signed char)_providerForVariant:(long long)variant lockConfig:(id)config homeConfig:(id)config;
- (void)beginChangeBatch;
- (_Bool)cachedVariantsShareWallpaperConfiguration;
- (id)cleanedProceduralWallpaperInfo:(id)info;
- (void)clearCacheForVariants:(long long)variants;
- (void)clearCacheForVariants:(long long)variants memoryOnly:(_Bool)only;
- (void)clearDelayedChangeNotifications;
- (CGRect)cropRectForOldCropRect:(CGRect)rect portrait:(_Bool)portrait zoomScale:(double)scale oldParallaxFactor:(double)factor forImageSize:(CGSize)size newZoomScale:(double *)scale;
- (CGRect)cropRectForViewPort:(CGRect)port portrait:(_Bool)portrait zoomScale:(double)scale parallaxFactor:(double)factor forImageSize:(CGSize)size contentScaleFactor:(double)factor;
- (id)dataStores;
- (void)dealloc;
- (void)delayNotifyingChangeForVariants:(long long)variants;
- (id)delegate;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (long long)effectiveSharedVariantForVariants:(long long)variants;
- (_Bool)enableWallpaperDimming;
- (void)endChangeBatch;
- (id)fallbackWallpaperConfigurationForVarient:(long long)varient;
- (void)getBestCropRect:(out CGRect *)rect zoomScale:(out double *)scale forImageSize:(CGSize)size portrait:(_Bool)portrait parallaxFactor:(double)factor;
- (id)getWallpaperLegibilitySettingsForVariant:(long long)variant;
- (_Bool)hasWallpaperImageForVariant:(long long)variant wallpaperMode:(long long)mode;
- (id)homeScreenWallpaperConfiguration;
- (id)homeScreenWallpaperConfigurationIncludingValuesForTypes:(unsigned long long)types;
- (id)init;
- (id)initWithWallpaperDataStores:(id)stores;
- (id)initWithWallpaperDataStores:(id)stores wallpaperSize:(CGSize)size scale:(double)scale sizeType:(long long)type;
- (_Bool)isCachedVariantsShareWallpaperConfigurationValid;
- (_Bool)isInChangeBatch;
- (_Bool)isProceduralWallpaperInfoValid:(id)valid;
- (_Bool)isVideoSupportedByDefaultForVariant:(long long)variant;
- (_Bool)isVideoSupportedForVariant:(long long)variant;
- (id)lockScreenWallpaperConfiguration;
- (id)lockScreenWallpaperConfigurationIncludingValuesForTypes:(unsigned long long)types;
- (id)magnifyMode;
- (void)migrateWallpaperOptionsForImageIfNecessaryForVariant:(long long)variant representingVariants:(long long)variants;
- (id)migratedWallpaperOptionsForWallpaperOptions:(id)options originalImageSize:(CGSize)size;
- (id)normalizeImage:(id)image;
- (void)notifyDelegateOfChangesToVariants:(long long)variants;
- (unsigned long long)numberOfCachedStaticImages;
- (long long)parallaxDeviceType;
- (double)parallaxFactorForCropRect:(CGRect)rect portrait:(_Bool)portrait forImageSize:(CGSize)size zoomScale:(double)scale;
- (void)performMigrationWithFailureHandler:(id /* block */)handler;
- (id)posterMigrationInfo;
- (Class)proceduralWallpaperClassForIdentifier:(id)identifier;
- (id)proceduralWallpaperInfoForVariant:(long long)variant;
- (id)proceduralWallpaperProvider;
- (void)regenerateStaticWallpaperThumbnailImages;
- (void)regenerateThumbnailIfNecessaryForVariant:(long long)variant wallpaperMode:(long long)mode;
- (void)regenerateThumbnailsIfNecessary;
- (void)removeAllDataExceptForType:(long long)type variants:(long long)variants variantsShareWallpaperConfiguration:(_Bool)configuration;
- (void)removeAllDataExceptForTypes:(unsigned long long)types variants:(long long)variants variantsShareWallpaperConfiguration:(_Bool)configuration;
- (void)removeDataForTypes:(unsigned long long)types variants:(long long)variants variantsShareWallpaperConfiguration:(_Bool)configuration;
- (void)removeProceduralWallpaperForVariants:(long long)variants;
- (void)removeVideoForVariants:(long long)variants;
- (void)removeWallpaperColorForVariants:(long long)variants;
- (void)removeWallpaperGradientForVariants:(long long)variants;
- (void)removeWallpaperImageDataTypes:(unsigned long long)types forVariants:(long long)variants;
- (void)removeWallpaperImageHashDataForVariants:(long long)variants;
- (void)removeWallpaperImagesForVariants:(long long)variants;
- (void)removeWallpaperImagesForVariants:(long long)variants variantsShareWallpaperConfiguration:(_Bool)configuration;
- (void)removeWallpaperOptionsForVariants:(long long)variants;
- (void)restoreDefaultWallpaperForAllVariantsAndNotify:(_Bool)notify;
- (void)safeMigrateWallpaperImageIfNecessary;
- (_Bool)safeMigrateWallpaperImageIfNecessaryForVariant:(long long)variant representingVariants:(long long)variants wallpaperMode:(long long)mode;
- (void)saveCroppedVideo:(id)video toURL:(id)url cropRect:(CGRect)rect completionHandler:(id /* block */)handler;
- (void)setCachedVariantsShareWallpaperConfiguration:(_Bool)configuration;
- (void)setCachedVariantsShareWallpaperConfigurationValid:(_Bool)valid;
- (void)setDelegate:(id)delegate;
- (void)setEnableWallpaperDimming:(_Bool)dimming;
- (void)setMagnifyMode:(id)mode;
- (_Bool)setProceduralWallpaperIdentifier:(id)identifier options:(id)options forVariants:(long long)variants;
- (void)setProceduralWallpaperProvider:(id)provider;
- (_Bool)setVideoURL:(id)url forVariant:(long long)variant shoudCrop:(_Bool)crop relativeCropRect:(CGRect)rect wallpaperMode:(long long)mode;
- (void)setWallpaperBundle:(id)bundle appearance:(id)appearance;
- (_Bool)setWallpaperColor:(id)color forVariants:(long long)variants;
- (_Bool)setWallpaperColorName:(id)name forVariants:(long long)variants;
- (_Bool)setWallpaperConfigurationFromDefaultWallpaperConfiguration:(id)configuration forVariants:(long long)variants wallpaperMode:(long long)mode name:(id)name;
- (_Bool)setWallpaperGradient:(id)gradient forVariants:(long long)variants;
- (_Bool)setWallpaperImage:(id)image adjustedImage:(id)image thumbnailData:(id)data imageHashData:(id)data wallpaperOptions:(id)options forVariants:(long long)variants wallpaperMode:(long long)mode;
- (_Bool)setWallpaperImage:(id)image originalImage:(id)image forVariants:(long long)variants options:(unsigned long long)options;
- (_Bool)setWallpaperImage:(id)image originalImage:(id)image thumbnailData:(id)data imageHashData:(id)data wallpaperOptions:(id)options forVariants:(long long)variants options:(unsigned long long)options wallpaperMode:(long long)mode isMigrating:(_Bool)migrating;
- (_Bool)setWallpaperImage:(id)image wallpaperOptions:(id)options forVariants:(long long)variants;
- (_Bool)setWallpaperImageHashData:(id)data forVariants:(long long)variants wallpaperMode:(long long)mode;
- (void)setWallpaperMode:(long long)mode;
- (_Bool)setWallpaperOptions:(id)options forVariants:(long long)variants;
- (_Bool)setWallpaperOptions:(id)options forVariants:(long long)variants wallpaperMode:(long long)mode;
- (_Bool)setWallpaperThumbnailData:(id)data forVariant:(long long)variant;
- (_Bool)setWallpaperThumbnailData:(id)data forVariant:(long long)variant wallpaperMode:(long long)mode;
- (_Bool)setWallpaperThumbnailFromFullsizeImage:(id)image forVariant:(long long)variant wallpaperMode:(long long)mode;
- (_Bool)shouldSetWallpaperImageHashData;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)thumbnailDataForImage:(id)image;
- (double)thumbnailWidth;
- (_Bool)variantsShareWallpaperConfiguration;
- (_Bool)variantsShareWallpaperConfigurationForTypes:(unsigned long long)types;
- (id)videoURLForVariant:(long long)variant wallpaperMode:(long long)mode;
- (id)wallpaperColorForVariant:(long long)variant fromDataStore:(id)store colorName:(id *)name;
- (id)wallpaperConfigurationForVariant:(long long)variant;
- (id)wallpaperConfigurationForVariant:(long long)variant includingValuesForTypes:(unsigned long long)types;
- (id)wallpaperConfigurationForVariant:(long long)variant includingValuesForTypes:(unsigned long long)types wallpaperMode:(long long)mode;
- (void)wallpaperDidChangeForVariants:(long long)variants shouldNotify:(_Bool)notify;
- (id)wallpaperImageForVariant:(long long)variant wallpaperMode:(long long)mode;
- (id)wallpaperImageHashDataForVariant:(long long)variant wallpaperMode:(long long)mode;
- (long long)wallpaperMode;
- (id)wallpaperOptionsForVariant:(long long)variant wallpaperMode:(long long)mode;
- (id)wallpaperOriginalImageForVariant:(long long)variant wallpaperMode:(long long)mode;
- (double)wallpaperScale;
- (CGSize)wallpaperSize;
- (CGSize)wallpaperSizeIncludingParallaxOverhang;
- (long long)wallpaperSizeType;
- (id)wallpaperThumbnailImageDataForFulfillingLookupForConfiguration:(id)configuration;
- (id)wallpaperThumbnailImageDataForVariant:(long long)variant wallpaperMode:(long long)mode;
- (id)wallpaperThumbnailImageDataForVariant:(long long)variant wallpaperMode:(long long)mode inDataStore:(id)store;
- (id)wallpaperThumbnailImageForFulfillingLookupForConfiguration:(id)configuration;
- (id)wallpaperThumbnailImageForVariant:(long long)variant wallpaperMode:(long long)mode;
- (long long)wallpaperTypeForSharedWallpaperConfigurationForTypes:(unsigned long long)types;
- (void)wallpaperWillChangeForVariants:(long long)variants;

@end

#endif /* PBUIWallpaperConfigurationManager_h */