//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PRSPosterUpdate_h
#define PRSPosterUpdate_h
@import Foundation;

#include "PRSPosterUpdatePayload.h"

@interface PRSPosterUpdate : NSObject <NSSecureCoding> {
    /* instance variables */
    PRSPosterUpdatePayload *_payload;
    unsigned long long _type;
}

@property (readonly, nonatomic) PRSPosterUpdatePayload *payload;
@property (readonly, nonatomic) unsigned long long type;

/* class methods */
+ (id)posterUpdateComplications:(id)complications;
+ (id)posterUpdateHomeScreenAppearance:(unsigned long long)appearance;
+ (id)posterUpdateHomeScreenColor:(id)color;
+ (id)posterUpdateHomeScreenGradient:(id)gradient;
+ (id)posterUpdateHomeScreenPosterLegibilityBlurWithValue:(_Bool)value;
+ (id)posterUpdateHomeScreenPosterProvider:(id)provider sessionInfo:(id)info;
+ (id)posterUpdateHomeScreenPosterWithImageAtURL:(id)url;
+ (id)posterUpdateInlineComplication:(id)complication;
+ (id)posterUpdateLegibilityBlurWithValue:(_Bool)value;
+ (id)posterUpdateLockScreenPosterWithImageAtURL:(id)url;
+ (id)posterUpdateMirroredHomeScreenLegibilityBlurWithValue:(_Bool)value;
+ (id)posterUpdatePosterWithSessionInfo:(id)info;
+ (id)posterUpdatesForDecoratedSessionInfo:(id)info;
+ (id)posterUpdatesForWFWallpaperConfiguration:(id)configuration;
+ (id)posterUpdatesForWFWallpaperConfiguration:(id)configuration sessionInfo:(id)info;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)_initWithUpdateType:(unsigned long long)type payload:(id)payload;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)payload;
- (unsigned long long)type;

@end

#endif /* PRSPosterUpdate_h */