//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PRSPosterDescriptor_h
#define PRSPosterDescriptor_h
@import Foundation;

#include "BSInvalidatable-Protocol.h"
#include "PRSPosterPath.h"

@interface PRSPosterDescriptor : NSObject {
    /* instance variables */
    PRSPosterPath *_path;
    id <BSInvalidatable> _pathValidityExtension;
}

@property (readonly, nonatomic) PRSPosterPath *_path;
@property (readonly, copy, nonatomic) NSURL *assetDirectory;
@property (readonly, copy, nonatomic) NSString *identifier;

/* instance methods */
- (id)_initWithPath:(id)path;
- (id)_path;
- (id)assetDirectory;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (id)identifier;
- (id)init;
- (_Bool)isEqual:(id)equal;
- (id)loadGalleryOptionsWithError:(out id *)error;
- (id)loadUserInfoWithError:(out id *)error;

@end

#endif /* PRSPosterDescriptor_h */