//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PRSPosterConfiguration_h
#define PRSPosterConfiguration_h
@import Foundation;

#include "BSInvalidatable-Protocol.h"
#include "BSXPCSecureCoding-Protocol.h"
#include "PRSPosterPath.h"

@interface PRSPosterConfiguration : NSObject <BSXPCSecureCoding, NSSecureCoding> {
    /* instance variables */
    PRSPosterPath *_path;
    id <BSInvalidatable> _pathValidityExtension;
}

@property (readonly, nonatomic) PRSPosterPath *_path;
@property (readonly, copy, nonatomic) NSURL *assetDirectory;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

/* class methods */
+ (_Bool)supportsBSXPCSecureCoding;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)_initWithPath:(id)path;
- (id)_path;
- (id)assetDirectory;
- (void)dealloc;
- (id)description;
- (void)encodeWithBSXPCCoder:(id)bsxpccoder;
- (void)encodeWithCoder:(id)coder;
- (unsigned long long)hash;
- (id)init;
- (id)initWithBSXPCCoder:(id)bsxpccoder;
- (id)initWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (id)loadUserInfoWithError:(out id *)error;
- (id)providerBundleIdentifier;
- (id)serverUUID;

@end

#endif /* PRSPosterConfiguration_h */