//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 17, SDK: 17, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 140.12.4.0.0
//

#ifndef PRSPosterConfigurationAttributes_h
#define PRSPosterConfigurationAttributes_h
@import Foundation;

#include "PRSPosterPath.h"

@interface PRSPosterConfigurationAttributes : NSObject {
    /* instance variables */
    NSString *_extensionIdentifier;
    NSFileManager *_fileManager;
    NSURL *_identifierURL;
    PRSPosterPath *_path;
    NSUUID *_posterUUID;
    NSURL *_providerURL;
}

@property (readonly, nonatomic) NSString *extensionIdentifier;
@property (readonly, copy, nonatomic) NSURL *identifierURL;
@property (readonly, nonatomic) PRSPosterPath *path;
@property (readonly, copy, nonatomic) NSUUID *posterUUID;
@property (readonly, copy, nonatomic) NSURL *providerURL;
@property (readonly, nonatomic) NSString *role;
@property (readonly, nonatomic) NSSet *snapshotURLs;

/* instance methods */
- (id)_initWithPath:(id)path extensionIdentifier:(id)identifier posterUUID:(id)uuid providerURL:(id)url fileManager:(id)manager;
- (id)extensionIdentifier;
- (id)identifierURL;
- (id)initWithConfiguration:(id)configuration;
- (id)initWithPath:(id)path extensionIdentifier:(id)identifier;
- (id)path;
- (id)posterUUID;
- (id)providerURL;
- (id)role;
- (id)snapshotURLs;

@end

#endif /* PRSPosterConfigurationAttributes_h */