//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PRSService_h
#define PRSService_h
@import Foundation;

@class BSServiceConnection;
@protocol BSServiceConnectionClient;

@interface PRSService : NSObject {
    /* instance variables */
    BSServiceConnection<BSServiceConnectionClient> *_serviceConnection;
}

/* instance methods */
- (void)_refreshPosterDescriptorsForExtension:(id)extension sessionInfo:(id)info completion:(id /* block */)completion;
- (void)_selectConfigurationAndRefreshSnapshot:(id)snapshot completion:(id /* block */)completion;
- (id)_serviceInterfaceWithError:(id *)error;
- (void)associateConfigurationMatchingUUID:(id)uuid focusModeActivityUUID:(id)uuid completion:(id /* block */)completion;
- (oneway void)clearMigrationFlags:(id /* block */)flags;
- (void)createAndSelectLegacyPosterConfigurationIfNeededWithCompletion:(id /* block */)completion;
- (void)createPosterConfigurationForProviderIdentifier:(id)identifier posterDescriptorIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)dealloc;
- (oneway void)deleteDataStoreWithCompletion:(id /* block */)completion;
- (void)deletePosterConfigurationsMatchingUUID:(id)uuid completion:(id /* block */)completion;
- (void)deletePosterDescriptorsForExtension:(id)extension completion:(id /* block */)completion;
- (oneway void)deleteSnapshots:(_Bool)snapshots completion:(id /* block */)completion;
- (oneway void)deleteTransientDataWithCompletion:(id /* block */)completion;
- (void)exportPosterConfigurationMatchingUUID:(id)uuid completion:(id /* block */)completion;
- (void)fetchActiveConfiguration:(id /* block */)configuration;
- (oneway void)fetchActivePosterConfiguration:(id /* block */)configuration;
- (void)fetchAssociatedHomeScreenPosterConfigurationUUID:(id)uuid completion:(id /* block */)completion;
- (oneway void)fetchContentCutoutBoundsForActivePosterWithOrientation:(long long)orientation completionHandler:(id /* block */)handler;
- (oneway void)fetchContentCutoutBoundsForPosterConfiguration:(id)configuration orientation:(long long)orientation completionHandler:(id /* block */)handler;
- (oneway void)fetchContentObstructionBoundsForActivePosterWithOrientation:(long long)orientation completionHandler:(id /* block */)handler;
- (oneway void)fetchContentObstructionBoundsForPosterConfiguration:(id)configuration orientation:(long long)orientation completionHandler:(id /* block */)handler;
- (void)fetchExtensionIdentifiersWithCompletion:(id /* block */)completion;
- (oneway void)fetchFocusUUIDForConfiguration:(id)configuration completion:(id /* block */)completion;
- (void)fetchGallery:(id /* block */)gallery;
- (oneway void)fetchLimitedOcclusionBoundsForPosterConfiguration:(id)configuration orientation:(long long)orientation completionHandler:(id /* block */)handler;
- (oneway void)fetchMaximalContentCutoutBoundsForOrientation:(long long)orientation completionHandler:(id /* block */)handler;
- (oneway void)fetchObscurableBoundsForPosterConfiguration:(id)configuration orientation:(long long)orientation completionHandler:(id /* block */)handler;
- (void)fetchPosterConfigurations:(id /* block */)configurations;
- (void)fetchPosterConfigurationsForExtension:(id)extension completion:(id /* block */)completion;
- (void)fetchPosterDescriptorsForExtension:(id)extension completion:(id /* block */)completion;
- (void)fetchPosterSnapshotsWithRequest:(id)request completion:(id /* block */)completion;
- (oneway void)fetchRuntimeAssertionState:(id /* block */)state;
- (void)fetchSelectedConfiguration:(id /* block */)configuration;
- (oneway void)fetchStaticPosterDescriptorsForExtension:(id)extension completion:(id /* block */)completion;
- (oneway void)gatherDataFreshnessState:(id /* block */)state;
- (void)importPosterConfigurationFromArchiveData:(id)data completion:(id /* block */)completion;
- (oneway void)ingestSnapshotCollection:(id)collection forPosterConfiguration:(id)configuration completion:(id /* block */)completion;
- (id)init;
- (void)notifyFocusModeDidChange:(id)change completion:(id /* block */)completion;
- (oneway void)notifyPosterBoardOfApplicationUpdatesWithCompletion:(id /* block */)completion;
- (oneway void)overnightUpdateWithCompletion:(id /* block */)completion;
- (void)prewarmWithCompletion:(id /* block */)completion;
- (void)pushPosterGalleryUpdate:(id)update completion:(id /* block */)completion;
- (void)pushToProactiveWithCompletion:(id /* block */)completion;
- (void)refreshPosterConfiguration:(id)configuration completion:(id /* block */)completion;
- (void)refreshPosterConfiguration:(id)configuration sessionInfo:(id)info completion:(id /* block */)completion;
- (void)refreshPosterConfigurationMatchingUUID:(id)uuid sessionInfo:(id)info completion:(id /* block */)completion;
- (void)refreshPosterDescriptorsForExtension:(id)extension completion:(id /* block */)completion;
- (void)refreshPosterDescriptorsForExtension:(id)extension sessionInfo:(id)info completion:(id /* block */)completion;
- (void)refreshSnapshotForGalleryItemsMatchingDescriptorIdentifier:(id)identifier extensionIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)refreshSnapshotForPosterConfiguration:(id)configuration completion:(id /* block */)completion;
- (void)refreshSnapshotForPosterConfigurationMatchingUUID:(id)uuid completion:(id /* block */)completion;
- (oneway void)removeAllFocusConfigurationsMatchingFocusUUID:(id)uuid completion:(id /* block */)completion;
- (void)retrieveGallery:(id /* block */)gallery;
- (oneway void)runMigration:(_Bool)migration completion:(id /* block */)completion;
- (id)serviceNotificationCenterWithError:(id *)error;
- (void)updatePosterConfiguration:(id)configuration update:(id)update completion:(id /* block */)completion;
- (void)updatePosterConfigurationMatchingUUID:(id)uuid updates:(id)updates completion:(id /* block */)completion;
- (void)updateToSelectedConfiguration:(id)configuration completion:(id /* block */)completion;
- (void)updateToSelectedConfigurationMatchingUUID:(id)uuid completion:(id /* block */)completion;

@end

#endif /* PRSService_h */