//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 5156.3.15.0.0
//

#ifndef PSSpecifier_h
#define PSSpecifier_h
@import Foundation;

@interface PSSpecifier : NSObject {
    /* instance variables */
    SEL _buttonAction;
    SEL _confirmationAction;
    SEL _confirmationAlternateAction;
    SEL _confirmationCancelAction;
    SEL _controllerLoadAction;
    NSString *_name;
    NSMutableDictionary *_properties;
    NSDictionary *_shortTitleDict;
    _Bool _showContentString;
    NSDictionary *_titleDict;
    id _userInfo;
    NSArray *_values;
    id _weakUserInfo;
    SEL action;
    long long autoCapsType;
    long long autoCorrectionType;
    SEL cancel;
    long long cellType;
    Class detailControllerClass;
    Class editPaneClass;
    SEL getter;
    long long keyboardType;
    SEL setter;
    id target;
    unsigned long long textFieldType;
}

@property (nonatomic) SEL buttonAction;
@property (nonatomic) long long cellType;
@property (nonatomic) SEL confirmationAction;
@property (nonatomic) SEL confirmationAlternateAction;
@property (nonatomic) SEL confirmationCancelAction;
@property (nonatomic) SEL controllerLoadAction;
@property (nonatomic) Class detailControllerClass;
@property (nonatomic) Class editPaneClass;
@property (retain, nonatomic) NSString *identifier;
@property (retain, nonatomic) NSString *name;
@property (retain, nonatomic) NSDictionary *shortTitleDictionary;
@property (nonatomic) _Bool showContentString;
@property (weak, nonatomic) id target;
@property (retain, nonatomic) NSDictionary *titleDictionary;
@property (retain, nonatomic) id userInfo;
@property (retain, nonatomic) NSArray *values;
@property (weak, nonatomic) id weakUserInfo;

/* class methods */
+ (long long)autoCapsTypeForString:(id)string;
+ (long long)autoCorrectionTypeForNumber:(id)number;
+ (id)deleteButtonSpecifierWithName:(id)name target:(id)target action:(SEL)action;
+ (id)emptyGroupSpecifier;
+ (id)groupSpecifierWithID:(id)id;
+ (id)groupSpecifierWithID:(id)id name:(id)name;
+ (id)groupSpecifierWithName:(id)name;
+ (long long)keyboardTypeForString:(id)string;
+ (id)preferenceSpecifierNamed:(id)named target:(id)target set:(SEL)set get:(SEL)get detail:(Class)detail cell:(long long)cell edit:(Class)edit;
+ (id)specifierWithSpecifier:(id)specifier;

/* instance methods */
- (void)_addLinkSpec:(id)spec;
- (void)addFooterHyperlinkWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range target:(id)target action:(SEL)action;
- (void)addFooterHyperlinkWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range url:(id)url;
- (SEL)buttonAction;
- (long long)cellType;
- (SEL)confirmationAction;
- (SEL)confirmationAlternateAction;
- (SEL)confirmationCancelAction;
- (SEL)controllerLoadAction;
- (id)description;
- (Class)detailControllerClass;
- (Class)editPaneClass;
- (_Bool)hasValidGetter;
- (_Bool)hasValidSetter;
- (id)identifier;
- (id)init;
- (id)initWithName:(id)name target:(id)target set:(SEL)set get:(SEL)get detail:(Class)detail cell:(long long)cell edit:(Class)edit;
- (_Bool)isEqualToSpecifier:(id)specifier;
- (SEL)legacyAction;
- (SEL)legacyCancel;
- (void)loadValuesAndTitlesFromDataSource;
- (id)name;
- (id)objectForKeyedSubscript:(id)subscript;
- (void)performButtonAction;
- (void)performConfirmationAction;
- (void)performConfirmationAlternateAction;
- (void)performConfirmationCancelAction;
- (void)performControllerLoadAction;
- (id)performGetter;
- (void)performLegacyAction;
- (void)performSetterWithValue:(id)value;
- (id)properties;
- (id)propertyForKey:(id)key;
- (void)removePropertyForKey:(id)key;
- (void)setButtonAction:(SEL)action;
- (void)setCellType:(long long)type;
- (void)setConfirmationAction:(SEL)action;
- (void)setConfirmationAlternateAction:(SEL)action;
- (void)setConfirmationCancelAction:(SEL)action;
- (void)setControllerLoadAction:(SEL)action;
- (void)setDetailControllerClass:(Class)_class;
- (void)setEditPaneClass:(Class)_class;
- (void)setIdentifier:(id)identifier;
- (void)setKeyboardType:(long long)type autoCaps:(long long)caps autoCorrection:(long long)correction;
- (void)setLegacyAction:(SEL)action;
- (void)setLegacyCancel:(SEL)cancel;
- (void)setName:(id)name;
- (void)setObject:(id)object forKeyedSubscript:(id)subscript;
- (void)setProperties:(id)properties;
- (void)setProperty:(id)property forKey:(id)key;
- (void)setShortTitleDictionary:(id)dictionary;
- (void)setShowContentString:(_Bool)string;
- (void)setTarget:(id)target;
- (void)setTitleDictionary:(id)dictionary;
- (void)setUserInfo:(id)info;
- (void)setValues:(id)values;
- (void)setValues:(id)values titles:(id)titles;
- (void)setValues:(id)values titles:(id)titles shortTitles:(id)titles;
- (void)setValues:(id)values titles:(id)titles shortTitles:(id)titles usingLocalizedTitleSorting:(_Bool)sorting;
- (void)setWeakUserInfo:(id)info;
- (void)setupIconImageWithBundle:(id)bundle;
- (void)setupIconImageWithPath:(id)path;
- (id)shortTitleDictionary;
- (_Bool)showContentString;
- (id)target;
- (long long)titleCompare:(id)compare;
- (id)titleDictionary;
- (id)userInfo;
- (id)values;
- (id)weakUserInfo;

@end

#endif /* PSSpecifier_h */