//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 5156.3.15.0.0
//

#ifndef PSTableCell_h
#define PSTableCell_h
@import Foundation;

#include "PSSpecifier.h"
#include "PSTableCellHighlightContext.h"

@class NSURLSession, UIImageView, UILongPressGestureRecognizer, UITableViewCell;

@interface PSTableCell : UITableViewCell {
    /* instance variables */
    int _alignment;
    _Bool _cellEnabled;
    _Bool _checked;
    UIImageView *_checkedImageView;
    NSArray *_constraints;
    PSTableCellHighlightContext *_customHighlightContext;
    _Bool _forceHideDisclosureIndicator;
    NSString *_hiddenTitle;
    _Bool _isCopyable;
    _Bool _lazyIcon;
    NSString *_lazyIconAppID;
    _Bool _lazyIconDontUnload;
    _Bool _lazyIconForceSynchronous;
    NSURL *_lazyIconURL;
    UILongPressGestureRecognizer *_longTapRecognizer;
    SEL _pAction;
    id _pTarget;
    _Bool _reusedCell;
    _Bool _shouldHideTitle;
    PSSpecifier *_specifier;
    long long _type;
    NSURLSession *_urlSession;
    id _value;
}

@property (retain, nonatomic) NSArray *constraints;
@property (nonatomic) _Bool forceHideDisclosureIndicator;
@property (nonatomic) _Bool isCopyable;
@property (retain, nonatomic) NSURL *lazyIconURL;
@property (retain, nonatomic) UILongPressGestureRecognizer *longTapRecognizer;
@property (nonatomic) _Bool reusedCell;
@property (retain, nonatomic) PSSpecifier *specifier;
@property (nonatomic) long long type;

/* class methods */
+ (Class)cellClassForSpecifier:(id)specifier;
+ (long long)cellStyle;
+ (long long)cellTypeFromString:(id)string;
+ (double)defaultCellHeight;
+ (id)reuseIdentifierForBasicCellTypes:(long long)types;
+ (id)reuseIdentifierForClassAndType:(long long)type;
+ (id)reuseIdentifierForSpecifier:(id)specifier;
+ (id)stringFromCellType:(long long)type;

/* instance methods */
- (id)_automationID;
- (id)_checkmarkImage:(_Bool)image;
- (id)_contentString;
- (id)_copyableText;
- (id)_disclosureChevronImage:(_Bool)image;
- (void)_invalidateHighlightContext;
- (void)_updateAccessoryTypeForSpecifier:(id)specifier;
- (id)_urlSession;
- (SEL)action;
- (id)blankIcon;
- (_Bool)canBeChecked;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)action withSender:(id)sender;
- (_Bool)canReload;
- (SEL)cellAction;
- (_Bool)cellEnabled;
- (void)cellRemovedFromView;
- (id)cellTarget;
- (id)constraints;
- (void)copy:(id)copy;
- (void)dealloc;
- (_Bool)forceHideDisclosureIndicator;
- (void)forceSynchronousIconLoadOnNextIconLoad;
- (id)getIcon;
- (id)getLazyIcon;
- (id)getLazyIconID;
- (void)highlightCellForDuration:(double)duration animateUnighlight:(_Bool)unighlight;
- (id)iconImageView;
- (id)initWithStyle:(long long)style reuseIdentifier:(id)identifier specifier:(id)specifier;
- (_Bool)isChecked;
- (_Bool)isCopyable;
- (void)layoutSubviews;
- (id)lazyIconQueue:(id)queue;
- (id)lazyIconURL;
- (void)longPressed:(id)pressed;
- (id)longTapRecognizer;
- (_Bool)modernLayoutEnabled;
- (void)prepareForReuse;
- (void)refreshCellContentsWithSpecifier:(id)specifier;
- (void)reloadWithSpecifier:(id)specifier animated:(_Bool)animated;
- (_Bool)reusedCell;
- (id)scriptingInfoWithChildren;
- (void)setAction:(SEL)action;
- (void)setAlignment:(int)alignment;
- (void)setCellAction:(SEL)action;
- (void)setCellEnabled:(_Bool)enabled;
- (void)setCellTarget:(id)target;
- (void)setChecked:(_Bool)checked;
- (void)setConstraints:(id)constraints;
- (void)setForceHideDisclosureIndicator:(_Bool)indicator;
- (void)setHighlighted:(_Bool)highlighted animated:(_Bool)animated;
- (void)setIcon:(id)icon;
- (void)setIsCopyable:(_Bool)copyable;
- (void)setLazyIconURL:(id)url;
- (void)setLongTapRecognizer:(id)recognizer;
- (void)setReusedCell:(_Bool)cell;
- (void)setSelected:(_Bool)selected animated:(_Bool)animated;
- (void)setShouldHideTitle:(_Bool)title;
- (void)setSpecifier:(id)specifier;
- (void)setTarget:(id)target;
- (void)setTitle:(id)title;
- (void)setType:(long long)type;
- (void)setValue:(id)value;
- (void)setValueChangedTarget:(id)target action:(SEL)action specifier:(id)specifier;
- (void)setupModernLayoutConstraints;
- (_Bool)shouldUseModernLayout;
- (id)specifier;
- (id)target;
- (double)textFieldOffset;
- (id)title;
- (id)titleLabel;
- (id)titleTextLabel;
- (long long)type;
- (id)value;
- (id)valueLabel;

@end

#endif /* PSTableCell_h */