//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 5156.3.15.0.0
//

#ifndef PSViewController_h
#define PSViewController_h
@import Foundation;

#include "PSController-Protocol.h"
#include "PSRootController.h"
#include "PSSpecifier.h"

@class UIViewController;

@interface PSViewController : UIViewController <PSController> {
    /* instance variables */
    UIViewController<PSController> *_parentController;
    PSRootController *_rootController;
    PSSpecifier *_specifier;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

/* instance methods */
- (_Bool)canBeShownFromSuspendedState;
- (void)didLock;
- (void)didUnlock;
- (void)didWake;
- (void)formSheetViewDidDisappear;
- (void)formSheetViewWillDisappear;
- (void)handleURL:(id)url;
- (void)handleURL:(id)url withCompletion:(id /* block */)completion;
- (id)init;
- (id)installCloudSyncButton:(id)button delegate:(id)delegate;
- (long long)navigationItemLargeTitleDisplayMode;
- (id)parentController;
- (void)popupViewDidDisappear;
- (void)popupViewWillDisappear;
- (void)pushController:(id)controller;
- (void)pushController:(id)controller animate:(_Bool)animate;
- (id)readPreferenceValue:(id)value;
- (id)rootController;
- (void)setParentController:(id)controller;
- (void)setPreferenceValue:(id)value specifier:(id)specifier;
- (void)setRootController:(id)controller;
- (void)setSpecifier:(id)specifier;
- (void)showController:(id)controller;
- (void)showController:(id)controller animate:(_Bool)animate;
- (id)specifier;
- (void)statusBarWillAnimateByHeight:(double)height;
- (void)suspend;
- (void)viewDidLoad;
- (void)willBecomeActive;
- (void)willResignActive;
- (void)willUnlock;

@end

#endif /* PSViewController_h */