//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 1045.15.0.0.0
//

#ifndef CABackdropLayer_h
#define CABackdropLayer_h
#import <QuartzCore/QuartzCore.h>

@protocol CABackdropLayerDelegate, CALayerDelegate;

@interface CABackdropLayer : CALayer {
    /* instance variables */
    _Bool _disablesOccludedBackdropBlurs;
}

@property _Bool allowsInPlaceFiltering;
@property struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } backdropRect;
@property _Bool captureOnly;
@property (weak) id <CABackdropLayerDelegate, CALayerDelegate> delegate;
@property _Bool disablesOccludedBackdropBlurs;
@property _Bool enabled;
@property (copy) NSString *groupName;
@property (copy) NSString *groupNamespace;
@property _Bool ignoresScreenClip;
@property double marginWidth;
@property _Bool reducesCaptureBitDepth;
@property double scale;
@property _Bool tracksLuma;
@property _Bool usesGlobalGroupNamespace;
@property double zoom;

/* class methods */
+ (_Bool)CA_automaticallyNotifiesObservers:(Class)observers;
+ (_Bool)_hasRenderLayerSubclass;
+ (id)defaultValueForKey:(id)key;

/* instance methods */
- (void *)_copyRenderLayer:(void *)layer layerFlags:(unsigned int)flags commitFlags:(unsigned int *)flags;
- (_Bool)_renderLayerDefinesProperty:(unsigned int)property;
- (unsigned int)_renderLayerPropertyAnimationFlags:(unsigned int)flags;
- (_Bool)allowsInPlaceFiltering;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })backdropRect;
- (_Bool)captureOnly;
- (void)didChangeValueForKey:(id)key;
- (_Bool)disablesOccludedBackdropBlurs;
- (id)groupName;
- (id)groupNamespace;
- (_Bool)ignoresScreenClip;
- (_Bool)isEnabled;
- (void)layerDidBecomeVisible:(_Bool)visible;
- (double)marginWidth;
- (_Bool)reducesCaptureBitDepth;
- (double)scale;
- (void)setAllowsInPlaceFiltering:(_Bool)filtering;
- (void)setBackdropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)setCaptureOnly:(_Bool)only;
- (void)setDisablesOccludedBackdropBlurs:(_Bool)blurs;
- (void)setEnabled:(_Bool)enabled;
- (void)setGroupName:(id)name;
- (void)setGroupNamespace:(id)_namespace;
- (void)setIgnoresScreenClip:(_Bool)clip;
- (void)setMarginWidth:(double)width;
- (void)setReducesCaptureBitDepth:(_Bool)depth;
- (void)setScale:(double)scale;
- (void)setTracksLuma:(_Bool)luma;
- (void)setUsesGlobalGroupNamespace:(_Bool)_namespace;
- (void)setZoom:(double)zoom;
- (_Bool)tracksLuma;
- (_Bool)usesGlobalGroupNamespace;
- (double)zoom;

@end

#endif /* CABackdropLayer_h */