//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 1045.15.0.0.0
//

#ifndef CAFilter_h
#define CAFilter_h
#import <Foundation/Foundation.h>

@interface CAFilter : NSObject <NSCopying, NSMutableCopying, NSSecureCoding> {
    /* instance variables */
    void * _attr;
    void * _cache;
    unsigned int _flags;
    NSString *_name;
    unsigned int _type;
}

@property _Bool accessibility;
@property _Bool cachesInputImage;
@property _Bool enabled;
@property (copy) NSString *name;
@property (readonly) NSString *type;

/* class methods */
+ (void)CAMLParserStartElement:(id)element;
+ (_Bool)automaticallyNotifiesObserversForKey:(id)key;
+ (id)filterTypes;
+ (id)filterWithName:(id)name;
+ (id)filterWithType:(id)type;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)CAMLParser:(id)camlparser setValue:(id)value forKey:(id)key;
- (id)CAMLTypeForKey:(id)key;
- (void *)CA_copyRenderValue;
- (_Bool)cachesInputImage;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)dealloc;
- (id)description;
- (_Bool)enabled;
- (void)encodeWithCAMLWriter:(id)camlwriter;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithName:(id)name;
- (id)initWithType:(id)type;
- (_Bool)isAccessibility;
- (_Bool)isEnabled;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (id)name;
- (void)setAccessibility:(_Bool)accessibility;
- (void)setCachesInputImage:(_Bool)image;
- (void)setDefaults;
- (void)setEnabled:(_Bool)enabled;
- (void)setName:(id)name;
- (void)setValue:(id)value forKey:(id)key;
- (id)type;
- (id)valueForKey:(id)key;

@end

#endif /* CAFilter_h */