//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PBUIWallpaperConfiguration_h
#define PBUIWallpaperConfiguration_h
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "PBUIWallpaperOptions.h"

@class UIColor, UIImage;
@class PBUIWallpaperGradient, PBUIWallpaperImage;
@protocol BSDescriptionProviding;

@interface PBUIWallpaperConfiguration : NSObject <NSCopying, NSSecureCoding> {
    /* instance variables */
    _Bool _needsInactiveAppearanceTreatment;
    _Bool _needsWallpaperDimmingTreatment;
    NSURL *_originalVideoURL;
    NSDictionary *_proceduralWallpaperInfo;
    long long _variant;
    NSURL *_videoURL;
    UIColor *_wallpaperColor;
    NSString *_wallpaperColorName;
    PBUIWallpaperGradient *_wallpaperGradient;
    PBUIWallpaperImage *_wallpaperImage;
    NSData *_wallpaperImageHashData;
    PBUIWallpaperOptions *_wallpaperOptions;
    UIImage *_wallpaperOriginalImage;
    UIImage *_wallpaperThumbnailImage;
    NSData *_wallpaperThumbnailImageData;
    long long _wallpaperType;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) _Bool needsInactiveAppearanceTreatment;
@property (nonatomic) _Bool needsWallpaperDimmingTreatment;
@property (copy, nonatomic) NSURL *originalVideoURL;
@property (readonly, copy, nonatomic) NSString *proceduralWallpaperIdentifier;
@property (copy, nonatomic) NSDictionary *proceduralWallpaperInfo;
@property (readonly, copy, nonatomic) NSDictionary *proceduralWallpaperOptions;
@property (readonly) Class superclass;
@property (readonly, nonatomic) long long variant;
@property (copy, nonatomic) NSURL *videoURL;
@property (copy, nonatomic) UIColor *wallpaperColor;
@property (copy, nonatomic) NSString *wallpaperColorName;
@property (copy, nonatomic) PBUIWallpaperGradient *wallpaperGradient;
@property (retain, nonatomic) PBUIWallpaperImage *wallpaperImage;
@property (copy, nonatomic) NSData *wallpaperImageHashData;
@property (copy, nonatomic) PBUIWallpaperOptions *wallpaperOptions;
@property (retain, nonatomic) UIImage *wallpaperOriginalImage;
@property (retain, nonatomic) UIImage *wallpaperThumbnailImage;
@property (copy, nonatomic) NSData *wallpaperThumbnailImageData;
@property (readonly, nonatomic) long long wallpaperType;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (void)encodeWithCoder:(id)coder;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)initWithVariant:(long long)variant type:(long long)type;
- (_Bool)isEqual:(id)equal;
- (_Bool)needsInactiveAppearanceTreatment;
- (_Bool)needsWallpaperDimmingTreatment;
- (id)originalVideoURL;
- (id)proceduralWallpaperIdentifier;
- (id)proceduralWallpaperInfo;
- (id)proceduralWallpaperOptions;
- (void)setNeedsInactiveAppearanceTreatment:(_Bool)treatment;
- (void)setNeedsWallpaperDimmingTreatment:(_Bool)treatment;
- (void)setOriginalVideoURL:(id)url;
- (void)setProceduralWallpaperInfo:(id)info;
- (void)setVideoURL:(id)url;
- (void)setWallpaperColor:(id)color;
- (void)setWallpaperColorName:(id)name;
- (void)setWallpaperGradient:(id)gradient;
- (void)setWallpaperImage:(id)image;
- (void)setWallpaperImageHashData:(id)data;
- (void)setWallpaperOptions:(id)options;
- (void)setWallpaperOriginalImage:(id)image;
- (void)setWallpaperThumbnailImage:(id)image;
- (void)setWallpaperThumbnailImageData:(id)data;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (long long)variant;
- (id)videoURL;
- (id)wallpaperColor;
- (id)wallpaperColorName;
- (id)wallpaperGradient;
- (id)wallpaperImage;
- (id)wallpaperImageHashData;
- (id)wallpaperOptions;
- (id)wallpaperOriginalImage;
- (id)wallpaperThumbnailImage;
- (id)wallpaperThumbnailImageData;
- (long long)wallpaperType;

@end

#endif /* PBUIWallpaperConfiguration_h */