//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PBUIWallpaperViewController_h
#define PBUIWallpaperViewController_h
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "TXPrivateTypes.h"
#import "PBUIWallpaperView.h"
#import "PBUIWallpaperConfigurationManager.h"

@class UITraitCollection, UIView, UIViewController;
@class PBUIWallpaperDefaultsDomain, PBUIWallpaperStyleInfo;
@protocol BSDefaultObserver, BSDescriptionProviding, BSInvalidatable;
@protocol PBUIIrisWallpaperPlaying, PBUILegacyWallpaperPresenting, PBUILegibilitySettingsProviderDelegate;
@protocol PBUIWallpaperConfigurationManagerDelegate, PBUIWallpaperLegibilityProviding;
@protocol PBUIWallpaperPresentingDelegate, PBUIWallpaperReachabilityCoordinating;
@protocol PBUIWallpaperViewDelegate, PBUIWallpaperViewInternalObserver, PTSettingsKeyObserver;

@interface PBUIWallpaperViewController : UIViewController {
    /* instance variables */
    NSString *_cachingIdentifier;
    id <BSInvalidatable> _colorSamplingAssertion;
    _Bool _colorSamplingDisabled;
    long long _disallowRasterizationBlockCount;
    NSMutableSet *_disallowRasterizationReasonsHomeVariant;
    NSMutableSet *_disallowRasterizationReasonsLockVariant;
    long long _displayedVariant;
    UITraitCollection *_fakeBlurViewOverrideTraitCollection;
    _Bool _fixedOrientation;
    NSMutableSet *_hideHomescreenWallpaperReasons;
    NSMutableSet *_hideLockscreenWallpaperReasons;
    NSHashTable *_homescreenBlurViews;
    NSHashTable *_homescreenObservers;
    NSMutableSet *_homescreenStyleChangeDelayReasons;
    PBUIWallpaperStyleInfo *_homescreenStyleInfo;
    PBUIWallpaperView *_homescreenWallpaperView;
    UIView *_inactiveAppearanceDimmingView;
    NSHashTable *_lockscreenBlurViews;
    NSHashTable *_lockscreenObservers;
    double _lockscreenOnlyWallpaperAlpha;
    PBUIWallpaperStyleInfo *_lockscreenStyleInfo;
    PBUIWallpaperView *_lockscreenWallpaperView;
    id <PBUIWallpaperReachabilityCoordinating> _reachabilityCoordinator;
    NSHashTable *_requireWallpaperAssertions;
    PBUIWallpaperView *_sharedWallpaperView;
    NSHashTable *_suspendColorSamplingAssertions;
    NSHashTable *_suspendWallpaperAnimationAssertions;
    PBUIWallpaperConfigurationManager *_wallpaperConfigurationManager;
    UIView *_wallpaperContainerView;
    PBUIWallpaperDefaultsDomain *_wallpaperDefaultsStore;
    id <BSDefaultObserver> _wallpaperEnableDimmingObserver;
    id <PBUIWallpaperPresentingDelegate> _wallpaperPresentingDelegate;
    NSHashTable *_wallpaperScaleAssertions;
    id <BSInvalidatable> _wallpaperStyleAnimationAssertion;
}

@property (nonatomic) long long activeVariant;
@property (copy, nonatomic) NSString *cachingIdentifier;
@property (nonatomic) _Bool colorSamplingDisabled;
@property (readonly, nonatomic) PBUIWallpaperStyleTransitionState currentHomescreenStyleTransitionState;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (retain, nonatomic) UITraitCollection *fakeBlurViewOverrideTraitCollection;
@property (nonatomic) _Bool fixedOrientation;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) PBUIWallpaperStyleInfo *homescreenStyleInfo;
@property (readonly, nonatomic) double homescreenWallpaperScale;
@property (retain, nonatomic) PBUIWallpaperView *homescreenWallpaperView;
@property (readonly, nonatomic) id <PBUIIrisWallpaperPlaying> irisWallpaperPlayer;
@property (readonly, nonatomic) PBUIWallpaperStyleInfo *lockscreenStyleInfo;
@property (readonly, nonatomic) double lockscreenWallpaperScale;
@property (retain, nonatomic) PBUIWallpaperView *lockscreenWallpaperView;
@property (readonly, nonatomic) double minimumHomescreenWallpaperScale;
@property (readonly, nonatomic) double minimumLockscreenWallpaperScale;
@property (retain, nonatomic) id <PBUIWallpaperReachabilityCoordinating> reachabilityCoordinator;
@property (retain, nonatomic) PBUIWallpaperView *sharedWallpaperView;
@property (readonly, nonatomic) unsigned long long significantEventsCounter;
@property (readonly) Class superclass;
@property (retain, nonatomic) PBUIWallpaperConfigurationManager *wallpaperConfigurationManager;
@property (weak, nonatomic) id <PBUIWallpaperPresentingDelegate> wallpaperPresentingDelegate;
@property (retain, nonatomic) id <BSInvalidatable> wallpaperStyleAnimationAssertion;

/* class methods */
+ (id)substitutionFlatColorForWallpaperName:(id)name;

/* instance methods */
- (void)_accessibilityReduceTransparencyChanged:(id)changed;
- (id)_activeWallpaperView;
- (void)_beginDisallowRasterizationBlock;
- (void)_beginSuspendingMotionEffectsForStyleIfNeeded;
- (unsigned long long)_bestWallpaperViewInitializationOptionsForVariant:(long long)variant shared:(_Bool)shared wallpaperOptions:(id)options options:(unsigned long long)options;
- (id)_blurViewsForVariant:(long long)variant;
- (_Bool)_canShowWhileLocked;
- (void)_clearWallpaperEffectView:(id)view;
- (void)_clearWallpaperView:(id)view;
- (void)_endDisallowRasterizationBlock;
- (void)_endSuspendingMotionEffectsForStyleIfNeeded;
- (void)_handleWallpaperChangedForVariant:(long long)variant;
- (void)_handleWallpaperLegibilitySettingsChanged:(id)changed forVariant:(long long)variant;
- (void)_invalidateWallpaperAssertion:(id)assertion;
- (_Bool)_isRasterizationDisallowedForCurrentVariant;
- (_Bool)_isWallpaperHiddenForVariant:(long long)variant;
- (_Bool)_isWallpaperView:(id)view displayingWallpaperWithConfiguration:(id)configuration forVariant:(long long)variant;
- (id)_makeWallpaperViewWithConfiguration:(id)configuration forVariant:(long long)variant shared:(_Bool)shared options:(unsigned long long)options;
- (id)_newWallpaperEffectViewForVariant:(long long)variant transitionState:(PBUIWallpaperStyleTransitionState)state;
- (id)_observersForVariant:(long long)variant;
- (void)_precacheStyles:(id)styles usingTraitCollection:(id)collection;
- (void)_reconfigureBlurViewsForVariant:(long long)variant;
- (void)_registerFakeBlurView:(id)view;
- (void)_removeColorSamplingAssertion:(id)assertion;
- (void)_removeWallpaperAnimationAssertion:(id)assertion;
- (_Bool)_setDisallowRasterization:(_Bool)rasterization withReason:(id)reason reasons:(id)reasons;
- (void)_setWallpaperHidden:(_Bool)hidden variant:(long long)variant reason:(id)reason;
- (_Bool)_shouldSuspendMotionEffectsForState:(PBUIWallpaperStyleTransitionState)state;
- (_Bool)_shouldSuspendMotionEffectsForStyle:(long long)style;
- (id)_sourceForFakeBlurView:(id)view;
- (void)_suspendOrResumeColorSampling;
- (void)_suspendOrResumeWallpaperAnimation;
- (void)_unregisterFakeBlurView:(id)view;
- (void)_updateAndPrewarmWallpapers;
- (void)_updateBlurGeneration;
- (void)_updateBlurImagesForVariant:(long long)variant;
- (_Bool)_updateEffectViewForVariant:(long long)variant oldState:(PBUIWallpaperStyleTransitionState *)state newState:(PBUIWallpaperStyleTransitionState *)state oldEffectView:(id *)view newEffectView:(id *)view;
- (_Bool)_updateEffectViewForVariant:(long long)variant withFactory:(id)factory;
- (void)_updateMotionEffectsForState:(PBUIWallpaperStyleTransitionState)state;
- (void)_updateRasterizationState;
- (void)_updateSeparateWallpaperForVariants:(long long)variants options:(unsigned long long)options wallpaperMode:(long long)mode;
- (void)_updateSharedWallpaperWithOptions:(unsigned long long)options wallpaperMode:(long long)mode;
- (void)_updateWallpaperForLocations:(long long)locations options:(unsigned long long)options wallpaperMode:(long long)mode withCompletion:(id /* block */)completion;
- (void)_updateWallpaperForWallpaperDimming:(_Bool)dimming;
- (void)_updateWallpaperForWallpaperMode:(long long)mode;
- (void)_updateWallpaperHidden;
- (void)_updateWallpaperParallax;
- (void)_updateWallpaperScaleWithAnimationFactory:(id)factory;
- (id)_vendWallpaperViewForConfiguration:(id)configuration forVariant:(long long)variant shared:(_Bool)shared options:(unsigned long long)options;
- (id)_wallpaperScaleAssertionForVariant:(long long)variant scale:(double)scale;
- (double)_wallpaperScaleForVariant:(long long)variant;
- (Class)_wallpaperViewClassForType:(long long)type;
- (long long)activeVariant;
- (void)addObserver:(id)observer forVariant:(long long)variant;
- (id)averageColorForVariant:(long long)variant;
- (id)averageColorInRect:(CGRect)rect forVariant:(long long)variant;
- (id)averageColorInRect:(CGRect)rect forVariant:(long long)variant withSmudgeRadius:(double)radius;
- (void)beginDelayingHomescreenStyleChangesForReason:(id)reason;
- (void)beginSimulatedLiveWallpaperTouchWithReason:(id)reason;
- (id)cachingIdentifier;
- (void)cancelInProcessAnimations;
- (void)cleanupOldSharedWallpaper:(id)wallpaper lockSreenWallpaper:(id)wallpaper homeScreenWallpaper:(id)wallpaper;
- (_Bool)colorSamplingDisabled;
- (double)contrastForVariant:(long long)variant;
- (double)contrastInRect:(CGRect)rect forVariant:(long long)variant;
- (PBUIWallpaperStyleTransitionState)currentHomescreenStyleTransitionState;
- (void)dealloc;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (void)endDelayingHomescreenStyleChangesForReason:(id)reason animationFactory:(id)factory;
- (void)endSimulatedLiveWallpaperTouchWithReason:(id)reason;
- (id)fakeBlurViewOverrideTraitCollection;
- (_Bool)fixedOrientation;
- (_Bool)homeScreenPosterMirrorsLock;
- (id)homescreenStyleInfo;
- (double)homescreenWallpaperScale;
- (id)homescreenWallpaperView;
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (id)irisWallpaperPlayer;
- (id)legibilitySettingsForVariant:(long long)variant;
- (id)lockscreenStyleInfo;
- (double)lockscreenWallpaperScale;
- (id)lockscreenWallpaperView;
- (double)minimumHomescreenWallpaperScale;
- (double)minimumLockscreenWallpaperScale;
- (double)minimumWallpaperScaleForVariant:(long long)variant;
- (id)newFakeBlurViewForVariant:(long long)variant style:(long long)style transformOptions:(unsigned long long)options;
- (void)noteDidRotateFromInterfaceOrientation:(long long)orientation;
- (void)noteWallpapersDidUpdate;
- (void)noteWillAnimateToInterfaceOrientation:(long long)orientation;
- (void)preheatWallpaperForVariant:(long long)variant;
- (void)providerLegibilitySettingsChanged:(id)changed;
- (id)reachabilityCoordinator;
- (void)removeObserver:(id)observer forVariant:(long long)variant;
- (void)removeWallpaperRequiredAssertion:(id)assertion;
- (_Bool)removeWallpaperStyleForPriority:(long long)priority forVariant:(long long)variant withAnimationFactory:(id)factory;
- (id)requireWallpaperRasterizationWithReason:(id)reason;
- (id)requireWallpaperWithReason:(id)reason;
- (void)setActiveVariant:(long long)variant;
- (void)setActiveVariant:(long long)variant withOutAnimationFactory:(id)factory inAnimationFactory:(id)factory completion:(id /* block */)completion;
- (void)setAlpha:(double)alpha forWallpaperVariant:(long long)variant;
- (void)setCachingIdentifier:(id)identifier;
- (void)setColorSamplingDisabled:(_Bool)disabled;
- (void)setDisallowsRasterization:(_Bool)rasterization forVariant:(long long)variant withReason:(id)reason;
- (void)setFakeBlurViewOverrideTraitCollection:(id)collection;
- (void)setFixedOrientation:(_Bool)orientation;
- (id)setHomescreenWallpaperScale:(double)scale withAnimationFactory:(id)factory;
- (void)setHomescreenWallpaperView:(id)view;
- (void)setLockscreenOnlyWallpaperAlpha:(double)alpha;
- (void)setLockscreenWallpaperContentsRect:(CGRect)rect;
- (id)setLockscreenWallpaperScale:(double)scale withAnimationFactory:(id)factory;
- (void)setLockscreenWallpaperView:(id)view;
- (void)setReachabilityCoordinator:(id)coordinator;
- (void)setSharedWallpaperView:(id)view;
- (void)setWallpaperConfigurationManager:(id)manager;
- (void)setWallpaperHidden:(_Bool)hidden variant:(long long)variant reason:(id)reason;
- (void)setWallpaperPresentingDelegate:(id)delegate;
- (_Bool)setWallpaperStyle:(long long)style forPriority:(long long)priority forVariant:(long long)variant withAnimationFactory:(id)factory;
- (void)setWallpaperStyleAnimationAssertion:(id)assertion;
- (_Bool)setWallpaperStyleTransitionState:(PBUIWallpaperStyleTransitionState)state forPriority:(long long)priority forVariant:(long long)variant withAnimationFactory:(id)factory;
- (void)settings:(id)settings changedValueForKey:(id)key;
- (id)sharedWallpaperView;
- (_Bool)shouldAutorotate;
- (_Bool)shouldDelayHomescreenStyleUpdates;
- (id)substitutionWallpaperConfigurationForWallpaperConfiguration:(id)configuration;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (unsigned long long)supportedInterfaceOrientations;
- (id)suspendColorSamplingForReason:(id)reason;
- (id)suspendWallpaperAnimationForReason:(id)reason;
- (void)traitCollectionDidChange:(id)change;
- (void)updateIrisWallpaperForInteractiveMode;
- (_Bool)updateIrisWallpaperForStaticMode;
- (void)updateWallpaperForLocations:(long long)locations wallpaperMode:(long long)mode withCompletion:(id /* block */)completion;
- (void)updateWallpaperForLocations:(long long)locations withCompletion:(id /* block */)completion;
- (_Bool)variantsShareWallpaper;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id)coordinator;
- (id)wallpaperConfigurationForUpdatingWallpaperViewsForVariant:(long long)variant wallpaperMode:(long long)mode;
- (id)wallpaperConfigurationForVariant:(long long)variant includingValuesForTypes:(unsigned long long)types wallpaperMode:(long long)mode;
- (id)wallpaperConfigurationManager;
- (void)wallpaperConfigurationManager:(id)manager didChangeWallpaperConfigurationForVariants:(long long)variants;
- (id)wallpaperConfigurationManager:(id)manager legibilitySettingsForVariant:(long long)variant;
- (unsigned long long)wallpaperDataTypesToRequestForUpdatingWallpaperViews;
- (void)wallpaperEffectImageForStyle:(long long)style variant:(long long)variant traitCollection:(id)collection result:(id /* block */)result;
- (id)wallpaperPresentingDelegate;
- (id)wallpaperStyleAnimationAssertion;
- (id)wallpaperStyleInfoForVariant:(long long)variant;
- (void)wallpaperView:(id)view didChangeZoomFactor:(double)factor;
- (id)wallpaperView:(id)view wallpaperConfigurationIncludingValueTypes:(unsigned long long)types;
- (void)wallpaperViewDidChangeWantsRasterization:(id)rasterization;
- (void)wallpaperViewDidInvalidateBlurs:(id)blurs;
- (id)wallpaperViewForVariant:(long long)variant;

@end

#endif /* PBUIWallpaperViewController_h */