//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PBUIWallpaperView_h
#define PBUIWallpaperView_h
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "TXPrivateTypes.h"

@class UIColor, UIImage, UIView, _UILegibilitySettings, _UILegibilitySettingsProvider;
@class PBUIWallpaperParallaxSettings, PBUIWallpaperPrototypeSettings;
@protocol PBUILegibilitySettingsProvider;
@protocol PBUILegibilitySettingsProviderDelegate;
@protocol PBUIWallpaperViewDelegate;
@protocol PBUIWallpaperViewInternalObserver;
@protocol PTSettingsKeyObserver;

@interface PBUIWallpaperView : UIView {
    /* instance variables */
    NSString *_cacheGroup;
    NSTimer *_colorSampleTimer;
    double _contentScaleFactor;
    UIView *_contentView;
    _Bool _continuousColorSamplingEnabled;
    id <PBUILegibilitySettingsProviderDelegate> _delegate;
    long long _disallowRasterizationBlockCount;
    _Bool _generatingBlurredImages;
    _Bool _hasVideo;
    id <PBUIWallpaperViewInternalObserver> _internalObserver;
    UIColor *_lastAverageColor;
    _UILegibilitySettings *_legibilitySettings;
    _UILegibilitySettingsProvider *_legibilitySettingsProvider;
    _Bool _needsWallpaperDimmingTreatment;
    _Bool _parallaxEnabled;
    double _parallaxFactor;
    PBUIWallpaperParallaxSettings *_parallaxSettings;
    UIView *_parallaxView;
    _Bool _rotating;
    _Bool _sharesContentsAcrossVariants;
    _Bool _shouldGenerateBlurredImagesWhenVisible;
    unsigned long long _transformOptions;
    UIImage *_untreatedWallpaperImage;
    long long _variant;
    _Bool _wallpaperAnimationEnabled;
    id <PBUIWallpaperViewDelegate> _wallpaperDelegate;
    long long _wallpaperMode;
    NSString *_wallpaperName;
    PBUIWallpaperPrototypeSettings *_wallpaperSettings;
    _Bool _wantsRasterization;
    double _zoomFactor;
}

@property (readonly, copy, nonatomic) NSString *cacheGroup;
@property (readonly, copy, nonatomic) NSString *cacheUniqueIdentifier;
@property (readonly, nonatomic) _Bool contentStatic;
@property (retain, nonatomic) UIView *contentView;
@property (nonatomic) _Bool continuousColorSamplingEnabled;
@property (readonly, nonatomic) CGRect cropRect;
@property (readonly, nonatomic) double cropZoomScale;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <PBUILegibilitySettingsProviderDelegate> delegate;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) _Bool handlesInactiveAppearanceTreatment;
@property (readonly, nonatomic) _Bool hasContentOutsideVisibleBounds;
@property (readonly, nonatomic) _Bool hasVideo;
@property (readonly) unsigned long long hash;
@property (weak, nonatomic) id <PBUIWallpaperViewInternalObserver> internalObserver;
@property (readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property (readonly, nonatomic) _Bool needsImmediateLayoutBeforeRotation;
@property (readonly, nonatomic) _Bool needsWallpaperDimmingTreatment;
@property (nonatomic) _Bool parallaxEnabled;
@property (nonatomic) double parallaxFactor;
@property (nonatomic) _Bool rotating;
@property (nonatomic) _Bool sharesContentsAcrossVariants;
@property (readonly) Class superclass;
@property (readonly, nonatomic) _Bool supportsCropping;
@property (nonatomic) unsigned long long transformOptions;
@property (retain, nonatomic) UIImage *untreatedWallpaperImage;
@property (nonatomic) long long variant;
@property (readonly, copy, nonatomic) NSString *variantCacheIdentifier;
@property (nonatomic) _Bool wallpaperAnimationEnabled;
@property (weak, nonatomic) id <PBUIWallpaperViewDelegate> wallpaperDelegate;
@property (readonly, nonatomic) UIImage *wallpaperImage;
@property (readonly, nonatomic) long long wallpaperMode;
@property (readonly, copy, nonatomic) NSString *wallpaperName;
@property (readonly, nonatomic) long long wallpaperType;
@property (nonatomic) double zoomFactor;

/* class methods */
+ (_Bool)_allowsRasterization;
+ (_Bool)_shouldScaleForParallax;
+ (_Bool)allowsParallax;
+ (Class)wallpaperViewClassForConfiguration:(id)configuration;
+ (Class)wallpaperViewClassForWallpaperType:(long long)type;

/* instance methods */
- (void)_addParallax;
- (void)_applyParallaxSettings;
- (id)_averageColorInContentViewRect:(CGRect)rect smudgeRadius:(double)radius;
- (id)_backdrop_generateImageFromImage:(id)image forBackdropParameters:(PBUIWallpaperBackdropParameters)parameters includeTint:(_Bool)tint traitCollection:(id)collection;
- (void)_beginDisallowRasterizationBlock;
- (id)_blurredImage;
- (id)_blurredImageURL;
- (id)_cacheKeyForParameters:(PBUIWallpaperBackdropParameters)parameters includingTint:(_Bool)tint downsampleFactor:(double)factor traitCollection:(id)collection;
- (id)_computeAverageColor;
- (double)_contrastInContentViewRect:(CGRect)rect contrastWithinBoxes:(double *)boxes contrastBetweenBoxes:(double *)boxes;
- (id)_displayedImage;
- (_Bool)_dontUseShadow;
- (void)_endDisallowRasterizationBlock;
- (id)_fallbackImageWithOriginalSize:(CGSize)size;
- (id)_generateImageFromImage:(id)image forBackdropParameters:(PBUIWallpaperBackdropParameters)parameters includeTint:(_Bool)tint traitCollection:(id)collection;
- (void)_handleVariantChange;
- (void)_handleVisibilityChange;
- (id)_imageForBackdropParameters:(PBUIWallpaperBackdropParameters)parameters includeTint:(_Bool)tint overrideTraitCollection:(id)collection;
- (id)_imageURLForBackdropParameters:(PBUIWallpaperBackdropParameters)parameters includeTint:(_Bool)tint overrideTraitCollection:(id)collection;
- (_Bool)_isParallaxActive;
- (_Bool)_isParallaxEnabled;
- (_Bool)_isParallaxMotionEnabled;
- (_Bool)_isVisible;
- (id)_material_generateImageFromImage:(id)image forBackdropParameters:(PBUIWallpaperBackdropParameters)parameters traitCollection:(id)collection;
- (_Bool)_needsFallbackImageForBackdropGeneratedImage:(id)image;
- (void)_notifyBlursInvalidated;
- (id)_primaryColorOverride;
- (void)_removeParallax;
- (void)_setLegibilitySettings:(id)settings notify:(_Bool)notify;
- (void)_startGeneratingBlurredImages;
- (void)_stopGeneratingBlurredImages;
- (void)_updateContentViewScale;
- (void)_updateGeneratingBlurs;
- (void)_updateLegibilitySettingsForAverageColor:(id)color force:(_Bool)force notify:(_Bool)notify;
- (void)_updateParallax;
- (void)_updateRasterizationState;
- (void)_updateScaleFactor;
- (id)averageColorInRect:(CGRect)rect withSmudgeRadius:(double)radius;
- (id)blurredImage;
- (id)blurredImageURL;
- (id)cacheGroup;
- (id)cacheUniqueIdentifier;
- (double)contentScaleFactor;
- (id)contentView;
- (_Bool)continuousColorSamplingEnabled;
- (double)contrast;
- (double)contrastInRect:(CGRect)rect;
- (double)contrastInRect:(CGRect)rect contrastWithinBoxes:(double *)boxes contrastBetweenBoxes:(double *)boxes;
- (CGRect)cropRect;
- (double)cropZoomScale;
- (void)dealloc;
- (id)delegate;
- (void)didMoveToWindow;
- (_Bool)handlesInactiveAppearanceTreatment;
- (_Bool)hasContentOutsideVisibleBounds;
- (_Bool)hasVideo;
- (id)imageForBackdropParameters:(PBUIWallpaperBackdropParameters)parameters includeTint:(_Bool)tint overrideTraitCollection:(id)collection;
- (id)imageURLForBackdropParameters:(PBUIWallpaperBackdropParameters)parameters includeTint:(_Bool)tint overrideTraitCollection:(id)collection;
- (id)initWithFrame:(CGRect)frame configuration:(id)configuration variant:(long long)variant cacheGroup:(id)group delegate:(id)delegate options:(unsigned long long)options;
- (id)internalObserver;
- (void)invalidate;
- (_Bool)isContentStatic;
- (_Bool)isDisplayingWallpaperWithConfiguration:(id)configuration forVariant:(long long)variant;
- (_Bool)isRotating;
- (void)layoutSubviews;
- (id)legibilitySettings;
- (void)legibilitySettingsDidChange;
- (_Bool)needsImmediateLayoutBeforeRotation;
- (_Bool)needsWallpaperDimmingTreatment;
- (_Bool)parallaxEnabled;
- (double)parallaxFactor;
- (void)preheatImageData;
- (void)prepareToAppear;
- (void)prepareToDisappear;
- (void)resetLegibilitySettingsForAverageColor:(id)color;
- (void)setContentView:(id)view;
- (void)setContentsRect:(CGRect)rect;
- (void)setContinuousColorSamplingEnabled:(_Bool)enabled;
- (void)setCropRect:(CGRect)rect zoomScale:(double)scale;
- (void)setDelegate:(id)delegate;
- (void)setGeneratesBlurredImages:(_Bool)images;
- (void)setHidden:(_Bool)hidden;
- (void)setInternalObserver:(id)observer;
- (void)setLegibilitySettings:(id)settings;
- (void)setParallaxEnabled:(_Bool)enabled;
- (void)setParallaxFactor:(double)factor;
- (void)setRotating:(_Bool)rotating;
- (void)setSharesContentsAcrossVariants:(_Bool)variants;
- (void)setTransformOptions:(unsigned long long)options;
- (void)setUntreatedWallpaperImage:(id)image;
- (void)setVariant:(long long)variant;
- (void)setVariant:(long long)variant withAnimationFactory:(id)factory;
- (void)setWallpaperAnimationEnabled:(_Bool)enabled;
- (void)setWallpaperDelegate:(id)delegate;
- (void)setZoomFactor:(double)factor;
- (void)setZoomFactor:(double)factor withAnimationFactory:(id)factory;
- (void)settings:(id)settings changedValueForKey:(id)key;
- (_Bool)sharesContentsAcrossVariants;
- (id)snapshotImage;
- (id)snapshotImageURL;
- (_Bool)supportsCropping;
- (unsigned long long)transformOptions;
- (id)untreatedWallpaperImage;
- (void)updateLegibilitySettingsForAverageColor:(id)color;
- (long long)variant;
- (id)variantCacheIdentifier;
- (_Bool)wallpaperAnimationEnabled;
- (id)wallpaperDelegate;
- (id)wallpaperImage;
- (long long)wallpaperMode;
- (id)wallpaperName;
- (long long)wallpaperType;
- (_Bool)wantsRasterization;
- (double)zoomFactor;

@end

#endif /* PBUIWallpaperView_h */