//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 64.128.1.0.0
//

#ifndef PBUIWallpaperOptions_h
#define PBUIWallpaperOptions_h
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@protocol BSDescriptionProviding;

@interface PBUIWallpaperOptions : NSObject <NSCopying, NSSecureCoding> {
    /* instance variables */
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _cropRect;
    _Bool _hasVideo;
    _Bool _magnifyEnabled;
    NSString *_name;
    double _parallaxFactor;
    _Bool _portrait;
    double _rotationAngle;
    double _stillTimeInVideo;
    _Bool _supportsCropping;
    _Bool _supportsRotation;
    NSDictionary *_wallpaperKitData;
    long long _wallpaperMode;
    long long _wallpaperStatus;
    double _zoomScale;
}

@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } cropRect;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) _Bool hasVideo;
@property (readonly) unsigned long long hash;
@property (nonatomic) _Bool magnifyEnabled;
@property (copy, nonatomic) NSString *name;
@property (readonly, nonatomic) _Bool parallaxEnabled;
@property (nonatomic) double parallaxFactor;
@property (readonly, copy, nonatomic) NSData *persistentDataRepresentation;
@property (nonatomic) _Bool portrait;
@property (nonatomic) double rotationAngle;
@property (nonatomic) double stillTimeInVideo;
@property (readonly) Class superclass;
@property (nonatomic) _Bool supportsCropping;
@property (nonatomic) _Bool supportsRotation;
@property (copy, nonatomic) NSDictionary *wallpaperKitData;
@property (nonatomic) long long wallpaperMode;
@property (nonatomic) long long wallpaperStatus;
@property (nonatomic) double zoomScale;

/* class methods */
+ (id)optionsWithName:(id)name parallaxFactor:(double)factor zoomScale:(double)scale supportsCropping:(_Bool)cropping cropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect portrait:(_Bool)portrait;
+ (id)optionsWithName:(id)name parallaxFactor:(double)factor zoomScale:(double)scale supportsCropping:(_Bool)cropping cropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect portrait:(_Bool)portrait hasVideo:(_Bool)video stillTimeInVideo:(double)video;
+ (id)optionsWithName:(id)name parallaxFactor:(double)factor zoomScale:(double)scale supportsCropping:(_Bool)cropping cropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect portrait:(_Bool)portrait hasVideo:(_Bool)video stillTimeInVideo:(double)video wallpaperKitData:(id)data;
+ (id)optionsWithName:(id)name parallaxFactor:(double)factor zoomScale:(double)scale supportsCropping:(_Bool)cropping cropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect portrait:(_Bool)portrait hasVideo:(_Bool)video stillTimeInVideo:(double)video wallpaperMode:(long long)mode wallpaperStatus:(long long)status;
+ (id)optionsWithName:(id)name parallaxFactor:(double)factor zoomScale:(double)scale supportsCropping:(_Bool)cropping cropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect portrait:(_Bool)portrait hasVideo:(_Bool)video stillTimeInVideo:(double)video wallpaperMode:(long long)mode wallpaperStatus:(long long)status wallpaperKitData:(id)data;
+ (id)optionsWithName:(id)name parallaxFactor:(double)factor zoomScale:(double)scale supportsCropping:(_Bool)cropping cropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect supportsRotation:(_Bool)rotation rotationAngle:(double)angle portrait:(_Bool)portrait hasVideo:(_Bool)video stillTimeInVideo:(double)video wallpaperMode:(long long)mode wallpaperStatus:(long long)status;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (struct CGSize { double x0; double x1; })bestWallpaperSizeForWallpaperSize:(struct CGSize { double x0; double x1; })size wallpaperScale:(double)scale deviceType:(long long)type imageScale:(double)scale;
- (id)copyWithZone:(struct _NSZone *)zone;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })cropRect;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (void)encodeWithCoder:(id)coder;
- (_Bool)hasVideo;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)initWithContentsOfURL:(id)url;
- (id)initWithName:(id)name parallaxFactor:(double)factor zoomScale:(double)scale supportsCropping:(_Bool)cropping cropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect supportsRotation:(_Bool)rotation rotationAngle:(double)angle portrait:(_Bool)portrait hasVideo:(_Bool)video stillTimeInVideo:(double)video wallpaperMode:(long long)mode wallpaperStatus:(long long)status wallpaperKitData:(id)data;
- (id)initWithPersistentDataRepresentation:(id)representation;
- (id)initWithStream:(id)stream;
- (_Bool)isEqual:(id)equal;
- (_Bool)isLooselyEqualToWallpaperOptions:(id)options;
- (_Bool)isMagnifyEnabled;
- (_Bool)isPortrait;
- (id)name;
- (_Bool)parallaxEnabled;
- (double)parallaxFactor;
- (id)persistentDataRepresentation;
- (id)persistentPropertyList;
- (double)rotationAngle;
- (void)setCropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)setHasVideo:(_Bool)video;
- (void)setMagnifyEnabled:(_Bool)enabled;
- (void)setName:(id)name;
- (void)setParallaxFactor:(double)factor;
- (void)setPortrait:(_Bool)portrait;
- (void)setRotationAngle:(double)angle;
- (void)setStillTimeInVideo:(double)video;
- (void)setSupportsCropping:(_Bool)cropping;
- (void)setSupportsRotation:(_Bool)rotation;
- (void)setWallpaperKitData:(id)data;
- (void)setWallpaperMode:(long long)mode;
- (void)setWallpaperStatus:(long long)status;
- (void)setZoomScale:(double)scale;
- (double)stillTimeInVideo;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (_Bool)supportsCropping;
- (_Bool)supportsRotation;
- (id)wallpaperKitData;
- (long long)wallpaperMode;
- (long long)wallpaperStatus;
- (_Bool)writeToURL:(id)url error:(id *)error;
- (double)zoomScale;

@end

#endif /* PBUIWallpaperOptions_h */