//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 15, Tool: ld (711)
//    - LC_SOURCE_VERSION: 4250.6.0.0.0
//

#ifndef SBFStaticWallpaperView_h
#define SBFStaticWallpaperView_h
#import <UIKit/UIKit.h>
#import "SBFWallpaperView.h"

@class UIImage;
@class SBFColorBoxes;

@interface SBFStaticWallpaperView : SBFWallpaperView {
    /* instance variables */
    SBFColorBoxes *_colorBoxes;
    UIImage *_displayedImage;
    NSData *_displayedImageHashData;
    NSString *_displayedImageHashString;
    NSURL *_displayedImageURL;
    double _overallContrast;
    UIImage *_sampleImage;
}

@property (retain, nonatomic) SBFColorBoxes *colorBoxes;
@property (retain, nonatomic) UIImage *displayedImage;
@property (copy, nonatomic) NSData *displayedImageHashData;
@property (copy, nonatomic) NSString *displayedImageHashString;
@property (retain, nonatomic) NSURL *displayedImageURL;
@property (retain, nonatomic) UIImage *sampleImage;

/* class methods */
+ (_Bool)_allowsParallax;
+ (_Bool)_allowsRasterization;
+ (_Bool)_canCacheImages;
+ (_Bool)_canDownscaleSampleImage;

/* instance methods */
- (id)_averageColorInContentViewRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect smudgeRadius:(double)radius;
- (id)_computeAverageColor;
- (double)_contrastInContentViewRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect contrastWithinBoxes:(double *)boxes contrastBetweenBoxes:(double *)boxes;
- (id)_createColorBoxes;
- (void)_displayImage:(id)image;
- (id)_displayedImage;
- (id)_displayedImageURL;
- (void)_generateImageForImage:(id)image cacheKey:(id)key options:(unsigned long long)options downsampleFactor:(double)factor needsDimmingTreatment:(_Bool)treatment averageColorProvider:(id /* block */)provider generationHandler:(id /* block */)handler;
- (struct CGSize { double x0; double x1; })_imageSize;
- (id)_sampleImage;
- (void)_setDisplayedImage:(id)image;
- (void)_setDisplayedImageURL:(id)url;
- (void)_setSampleImage:(id)image;
- (void)_setUpStaticImageContentView:(id)view;
- (void)_setupContentViewWithOptions:(unsigned long long)options;
- (void)_setupWallpaperImageFromConfiguration:(id)configuration options:(unsigned long long)options;
- (void)_updateColorBoxesWithKey:(id)key image:(id)image;
- (id)_wallpaperImageForAnalysis;
- (float)_zoomScale;
- (id)cacheUniqueIdentifier;
- (id)colorBoxes;
- (double)contrast;
- (double)contrastInRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect contrastWithinBoxes:(double *)boxes contrastBetweenBoxes:(double *)boxes;
- (double)cropZoomScale;
- (id)displayedImageHashData;
- (id)displayedImageHashString;
- (_Bool)hasContentOutsideVisibleBounds;
- (_Bool)imageRequiresLuminanceTreatment;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame configuration:(id)configuration variant:(long long)variant cacheGroup:(id)group delegate:(id)delegate options:(unsigned long long)options;
- (_Bool)isDisplayingWallpaperWithConfiguration:(id)configuration forVariant:(long long)variant;
- (void)preheatImageData;
- (void)setColorBoxes:(id)boxes;
- (void)setContentsRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)setCropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect zoomScale:(double)scale;
- (void)setDisplayedImageHashData:(id)data;
- (void)setDisplayedImageHashString:(id)string;
- (id)snapshotImage;
- (id)snapshotImageURL;
- (id)wallpaperImage;
- (long long)wallpaperType;

@end

#endif /* SBFStaticWallpaperView_h */