//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 4344.144.0.0.0
//

#ifndef SBFWallpaperView_h
#define SBFWallpaperView_h
#import <UIKit/UIKit.h>
#import "PBUIWallpaperView.h"

@interface SBFWallpaperView : PBUIWallpaperView

@end

#endif /* SBFWallpaperView_h */