//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 4344.144.0.0.0
//

#ifndef SBHomeScreenViewController_h
#define SBHomeScreenViewController_h
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class SBFZStackParticipant, SBHIconManager, UIView, UIViewController, _UILegibilitySettings;
@class SBIconController, SBUIController, SBFloatingDockBehaviorAssertion, SBWindowSceneStatusBarSettingsAssertion;
@protocol BSInvalidatable, SBFZStackParticipantDelegate, SBFloatingDockControllerObserver;

@interface SBHomeScreenViewController : UIViewController {
    /* instance variables */
    SBUIController *_UIController;
    NSMapTable *_appIconForceTouchControllerOrientationUpdateDeferralAssertions;
    NSMapTable *_appIconForceTouchControllerWindowLevelAssertions;
    SBWindowSceneStatusBarSettingsAssertion *_childOrPresentedStatusBarAssertion;
    UIView *_contentView;
    _Bool _disableAnimationForNextIconRotation;
    _Bool _homeScreenAutorotatesEvenWhenIconIsDragging;
    SBFloatingDockBehaviorAssertion *_homeScreenFloatingDockAssertion;
    SBIconController *_iconController;
    _Bool _iconControllerHidden;
    SBHIconManager *_iconManager;
    NSMutableSet *_iconRotationPreventionReasons;
    SBFloatingDockBehaviorAssertion *_widgetEditFloatingDockAssertion;
    id <BSInvalidatable> _widgetEditViewControllerOrientationUpdateDeferralAssertion;
    SBFZStackParticipant *_zStackParticipant;
}

@property (readonly, weak, nonatomic) SBUIController *UIController;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) _Bool homeScreenAutorotatesEvenWhenIconIsDragging;
@property (retain, nonatomic) SBFloatingDockBehaviorAssertion *homeScreenFloatingDockAssertion;
@property (readonly, weak, nonatomic) SBIconController *iconController;
@property (nonatomic) _Bool iconControllerHidden;
@property (readonly, weak, nonatomic) SBHIconManager *iconManager;
@property (retain, nonatomic) _UILegibilitySettings *legibilitySettings;
@property (readonly) Class superclass;
@property (retain, nonatomic) SBFloatingDockBehaviorAssertion *widgetEditFloatingDockAssertion;
@property (retain, nonatomic) id <BSInvalidatable> widgetEditViewControllerOrientationUpdateDeferralAssertion;
@property (retain, nonatomic) SBFZStackParticipant *zStackParticipant;

/* instance methods */
- (id)UIController;
- (void)_acquireFloatingDockBehaviorAssertionIfNecessaryForFloatingDockController:(id)controller;
- (void)_acquireForceTouchOrientationUpdateDeferralAssertionForIconView:(id)view;
- (void)_acquireForceTouchWindowLevelAssertionForIconView:(id)view;
- (void)_animateTransitionToSize:(struct CGSize { double x0; double x1; })size andInterfaceOrientation:(long long)orientation withTransitionContext:(id)context;
- (void)_appIconForceTouchControllerDidDismissNotification:(id)notification;
- (void)_appIconForceTouchControllerWillPresentNotification:(id)notification;
- (id)_autorotationPreventionReasons;
- (void)_cleanupAfterTransitionToSize:(struct CGSize { double x0; double x1; })size fromInterfaceOrientation:(long long)orientation withTransitionContext:(id)context;
- (void)_dismissAllIconForceTouchControllersDidFire:(id)fire;
- (id)_homeScreenView;
- (void)_iconEditingDidChange:(id)change;
- (void)_prepareForTransitionToSize:(struct CGSize { double x0; double x1; })size andInterfaceOrientation:(long long)orientation withTransitionCoordinator:(id)coordinator;
- (void)_relinquishForceTouchOrientationUpdateDeferralAssertionForIconView:(id)view;
- (void)_relinquishForceTouchWindowLevelAssertionForIconView:(id)view;
- (void)_widgetEditViewDidDisappear:(id)disappear;
- (void)_widgetEditViewDidDisappearImplementation;
- (void)_widgetEditViewWillAppear:(id)appear;
- (void)dealloc;
- (void)disableAnimationForNextIconRotation;
- (void)floatingDockControllerDidRegister:(id)_register;
- (_Bool)homeScreenAutorotatesEvenWhenIconIsDragging;
- (id)homeScreenFloatingDockAssertion;
- (id)iconController;
- (id)iconManager;
- (id)initWithCoder:(id)coder;
- (id)initWithIconController:(id)controller UIController:(id)uicontroller;
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (_Bool)isIconControllerHidden;
- (id)legibilitySettings;
- (void)loadView;
- (void)nudgeIconInterfaceOrientation:(long long)orientation duration:(double)duration;
- (void)setAllowIconRotation:(_Bool)rotation forReason:(id)reason;
- (void)setHomeScreenAutorotatesEvenWhenIconIsDragging:(_Bool)dragging;
- (void)setHomeScreenFloatingDockAssertion:(id)assertion;
- (void)setIconControllerHidden:(_Bool)hidden;
- (void)setLegibilitySettings:(id)settings;
- (void)setNeedsStatusBarAppearanceUpdate;
- (void)setWidgetEditFloatingDockAssertion:(id)assertion;
- (void)setWidgetEditViewControllerOrientationUpdateDeferralAssertion:(id)assertion;
- (void)setZStackParticipant:(id)participant;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewDidDisappear:(_Bool)disappear;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })size withTransitionCoordinator:(id)coordinator;
- (id)widgetEditFloatingDockAssertion;
- (id)widgetEditViewControllerOrientationUpdateDeferralAssertion;
- (id)zStackParticipant;
- (void)zStackParticipant:(id)participant updatePreferences:(id)preferences;
- (void)zStackParticipantDidChange:(id)change;

@end

#endif /* SBHomeScreenViewController_h */