//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 4344.144.0.0.0
//

#ifndef SBLockScreenViewControllerBase_h
#define SBLockScreenViewControllerBase_h
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class SBFLegacyWallpaperWakeAnimator, SBFLockScreenActionContext, UIViewController, UIVisualEffectView;
@protocol SBApplicationHosting, SBAutoUnlockRule, SBBiometricUnlockBehavior, SBBiometricUnlockBehaviorDelegate;
@protocol SBButtonEventsHandler, SBCoverSheetSlidingViewControllerContentViewController;
@protocol SBIdleTimerCoordinating, SBIdleTimerProviding;
@protocol SBLockScreenBacklightControlling, SBLockScreenBehaviorSuppressing, SBLockScreenBlockedStateObserving;
@protocol SBLockScreenButtonObserving, SBLockScreenCallHandling, SBLockScreenContentStateProviding;
@protocol SBLockScreenCustomActionStoring, SBLockScreenIdleTimerControlling, SBLockScreenLockingAndUnlocking;
@protocol SBLockScreenMediaControlsPresenting, SBLockScreenPasscodeViewPresenting, SBLockScreenPluginPresenting;
@protocol SBLockScreenProximityBehaviorProviding, SBLockScreenSpotlightPresenting, SBLockScreenStatusBarTransitioning;

@interface SBLockScreenViewControllerBase : UIViewController {
    /* instance variables */
    _Bool _authenticated;
    double _backlightLevel;
    id <SBBiometricUnlockBehaviorDelegate> _biometricUnlockBehaviorDelegate;
    SBFLockScreenActionContext *_customLockScreenActionContext;
    _Bool _expectsFaceContact;
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    SBFLegacyWallpaperWakeAnimator *_legacyWallpaperWakeAnimator;
    UIVisualEffectView *_wakeEffectView;
}

@property (nonatomic) _Bool authenticated;
@property (nonatomic) double backlightLevel;
@property (readonly, nonatomic) long long backlightLuminance;
@property (weak, nonatomic) id <SBBiometricUnlockBehaviorDelegate> biometricUnlockBehaviorDelegate;
@property (readonly, nonatomic) _Bool contentOccludesBackground;
@property (retain, nonatomic) SBFLockScreenActionContext *customLockScreenActionContext;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) _Bool expectsFaceContact;
@property (readonly) unsigned long long hash;
@property (weak, nonatomic) id <SBIdleTimerCoordinating> idleTimerCoordinator;
@property (readonly, nonatomic) SBFLegacyWallpaperWakeAnimator *legacyWallpaperWakeAnimator;
@property (readonly, nonatomic) _Bool shouldShowLockStatusBarTime;
@property (nonatomic) _Bool showingMediaControls;
@property (readonly) Class superclass;
@property (weak, nonatomic) UIVisualEffectView *wakeEffectView;

/* instance methods */
- (id)_customLockScreenActionContext;
- (double)backlightLevel;
- (long long)backlightLuminance;
- (id)biometricUnlockBehaviorDelegate;
- (_Bool)canBeDeactivatedForUIUnlockFromSource:(int)source;
- (_Bool)canHostAnApp;
- (void)conformsToSBApplicationHosting;
- (void)conformsToSBCoverSheetSlidingViewControllerContentViewController;
- (_Bool)contentOccludesBackground;
- (id)coordinatorRequestedIdleTimerBehavior:(id)behavior;
- (id)createHomeButtonShowPasscodeRecognizerForHomeButtonPress;
- (id)createHomeButtonSuppressAfterUnlockRecognizerForUnlockSource:(int)source;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (void)disableLockScreenPluginWithContext:(id)context;
- (void)emergencyDialerExitedWithError:(id)error;
- (void)enableLockScreenPluginWithContext:(id)context;
- (void)exitEmergencyDialerAnimated:(_Bool)animated;
- (_Bool)expectsFaceContact;
- (void)finishUIUnlockFromSource:(int)source;
- (void)handleBiometricEvent:(unsigned long long)event;
- (_Bool)handleHeadsetButtonPress:(_Bool)press;
- (_Bool)handleHomeButtonDoublePress;
- (_Bool)handleHomeButtonLongPress;
- (_Bool)handleHomeButtonPress;
- (_Bool)handleLockButtonPress;
- (_Bool)handleVoiceCommandButtonPress;
- (_Bool)handleVolumeDownButtonPress;
- (_Bool)handleVolumeUpButtonPress;
- (id)hostedAppSceneHandle;
- (id)hostedAppSceneHandles;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)orientation;
- (id)idleTimerCoordinator;
- (_Bool)isAuthenticated;
- (_Bool)isHostingAnApp;
- (_Bool)isInScreenOffMode;
- (_Bool)isMainPageVisible;
- (_Bool)isMakingEmergencyCall;
- (_Bool)isPasscodeLockVisible;
- (_Bool)isShowingMediaControls;
- (_Bool)isUnlockDisabled;
- (void)jiggleLockIcon;
- (void)launchEmergencyDialer;
- (void)launchEmergencyDialerAnimated:(_Bool)animated;
- (id)legacyWallpaperWakeAnimator;
- (void)noteDeviceBlockedStatusUpdated;
- (void)noteMenuButtonDown;
- (void)noteMenuButtonUp;
- (void)noteResetRestoreStateUpdated;
- (void)prepareForUILock;
- (void)prepareForUIUnlock;
- (void)presentOrDismissCoverSheetSpotlightAnimated:(_Bool)animated;
- (void)setAuthenticated:(_Bool)authenticated;
- (void)setBacklightLevel:(double)level;
- (void)setBiometricUnlockBehaviorDelegate:(id)delegate;
- (void)setCustomLockScreenActionContext:(id)context;
- (void)setIdleTimerCoordinator:(id)coordinator;
- (void)setInScreenOffMode:(_Bool)mode;
- (void)setInScreenOffMode:(_Bool)mode forAutoUnlock:(_Bool)unlock fromUnlockSource:(int)source;
- (void)setInScreenOffMode:(_Bool)mode preservingCoverSheetPresentationState:(_Bool)state;
- (void)setPasscodeLockVisible:(_Bool)visible animated:(_Bool)animated;
- (void)setPasscodeLockVisible:(_Bool)visible animated:(_Bool)animated completion:(id /* block */)completion;
- (void)setShowingMediaControls:(_Bool)controls;
- (void)setWakeEffectView:(id)view;
- (_Bool)shouldAutoUnlockForSource:(int)source;
- (_Bool)shouldDisableALS;
- (_Bool)shouldPresentOrDismissCoverSheetSpotlight;
- (_Bool)shouldShowLockStatusBarTime;
- (_Bool)shouldUnlockUIOnKeyDownEvent;
- (void)startLockScreenFadeInAnimationForSource:(int)source;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (_Bool)suppressesBanners;
- (_Bool)suppressesControlCenter;
- (_Bool)suppressesScreenshots;
- (void)updateScaleViewWithScale:(double)scale withDuration:(double)duration;
- (void)updateStatusBarForLockScreenComeback;
- (void)updateStatusBarForLockScreenTeardown;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id)coordinator;
- (id)wakeEffectView;
- (_Bool)willUIUnlockFromSource:(int)source;

@end

#endif /* SBLockScreenViewControllerBase_h */