//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 4344.144.0.0.0
//

#ifndef SBLockStateAggregator_h
#define SBLockStateAggregator_h
#import <Foundation/Foundation.h>

@class SBFAnalyticsClient;

@interface SBLockStateAggregator : NSObject {
    /* instance variables */
    SBFAnalyticsClient *_analyticsClient;
    unsigned long long _lockState;
}

@property (weak, nonatomic) SBFAnalyticsClient *analyticsClient;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)_descriptionForLockState:(unsigned long long)state;
- (id)_initWithAnalyticsClient:(id)client;
- (void)_updateLockState;
- (id)analyticsClient;
- (void)dealloc;
- (id)description;
- (_Bool)hasAnyLockState;
- (id)init;
- (unsigned long long)lockState;
- (void)setAnalyticsClient:(id)client;

@end

#endif /* SBLockStateAggregator_h */