//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 4344.144.0.0.0
//

#ifndef SBWallpaperController_h
#define SBWallpaperController_h
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "TXPrivateTypes.h"
#import "PBUIWallpaperViewController.h"
#import "PBUIWallpaperConfigurationManager.h"

@class FCActivityManager, PRSPosterConfiguration, PRSService, PTSingleTestRecipe, SBWindowScene;
@class SBFWallpaperAggdLogger, SBFWallpaperCoreAnalyticsLogger, UIGestureRecognizer, UIView, UIWindow;
@protocol BSDescriptionProviding, BSInvalidatable;
@protocol CSWallpaperSnapshotUpdating, FCActivityManagerObserving;
@protocol PBUIIrisWallpaperPlaying, PBUILegacyWallpaperPresenting, PBUILegibilitySettingsProviderDelegate;
@protocol PBUIWallpaperLegibilityProviding, PBUIWallpaperPresenting, PBUIWallpaperPresentingDelegate;
@protocol PBUIWallpaperReachabilityCoordinating, PBUIWallpaperViewDelegate;
@protocol SBFBacklightEnvironmentSceneProviding, SBUIActiveOrientationObserver, SBWallpaperServerDelegate;
@protocol UIWindowDelegate, _UISettingsKeyObserver;

@interface SBWallpaperController : NSObject {
    /* instance variables */
    PRSPosterConfiguration *_activeHomeScreenPosterConfiguration;
    PRSPosterConfiguration *_activeLockScreenPosterConfiguration;
    NSMutableSet *_activeOrientationSources;
    FCActivityManager *_activityManager;
    id <BSInvalidatable> _batterySaverAnimationAssertion;
    NSString *_cachingIdentifier;
    long long _displayedVariant;
    UITraitCollection *_fakeBlurViewOverrideTraitCollection;
    PTSingleTestRecipe *_migrationTestRecipe;
    long long _orientation;
    NSMapTable *_orientationProviders;
    PRSService *_posterBoardService;
    PTSingleTestRecipe *_reloadTestRecipe;
    UIViewController *_rootWallpaperViewController;
    SBFWallpaperAggdLogger *_wallpaperAggdLogger;
    PBUIWallpaperConfigurationManager *_wallpaperConfigurationManager;
    UIView *_wallpaperContainerView;
    SBFWallpaperCoreAnalyticsLogger *_wallpaperCoreAnalyticsLogger;
    id <PBUIWallpaperLegibilityProviding> _wallpaperLegibilityProvider;
    _Bool _wallpaperObscured;
    UIView *_wallpaperOverlayContainerView;
    id <PBUIWallpaperPresenting> _wallpaperPresenter;
    id <PBUIWallpaperPresentingDelegate> _wallpaperPresentingDelegate;
    id <BSInvalidatable> _wallpaperStyleAnimationAssertion;
    PBUIWallpaperViewController *_wallpaperViewController;
    UIWindow *_wallpaperWindow;
    SBWindowScene *_windowScene;
}

@property (readonly, nonatomic) long long _orientation;
@property (readonly, nonatomic) long long activeOrientationSource;
@property (nonatomic) long long activeVariant;
@property (retain, nonatomic) id <BSInvalidatable> batterySaverAnimationAssertion;
@property (readonly, copy, nonatomic) NSString *cachingIdentifier;
@property (readonly, nonatomic) PBUIWallpaperStyleTransitionState currentHomescreenStyleTransitionState;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) double effectiveReachabilityYOffset;
@property (retain, nonatomic) UITraitCollection *fakeBlurViewOverrideTraitCollection;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) double homescreenWallpaperScale;
@property (readonly, nonatomic) id <PBUIIrisWallpaperPlaying> irisWallpaperPlayer;
@property (readonly, nonatomic) id <PBUIWallpaperLegibilityProviding> legibilityProvider;
@property (readonly, nonatomic) double lockscreenWallpaperScale;
@property (readonly, nonatomic) double minimumHomescreenWallpaperScale;
@property (readonly, nonatomic) double minimumLockscreenWallpaperScale;
@property (readonly, nonatomic) id <PBUIWallpaperPresenting> presenter;
@property (readonly, nonatomic) unsigned long long significantEventsCounter;
@property (readonly) Class superclass;
@property (retain, nonatomic) SBFWallpaperAggdLogger *wallpaperAggdLogger;
@property (readonly, nonatomic) PBUIWallpaperConfigurationManager *wallpaperConfigurationManager;
@property (retain, nonatomic) SBFWallpaperCoreAnalyticsLogger *wallpaperCoreAnalyticsLogger;
@property (readonly, nonatomic) UIGestureRecognizer *wallpaperGestureRecognizer;
@property (weak, nonatomic) id <PBUIWallpaperPresentingDelegate> wallpaperPresentingDelegate;
@property (retain, nonatomic) id <BSInvalidatable> wallpaperStyleAnimationAssertion;
@property (nonatomic) double windowLevel;
@property (weak, nonatomic) SBWindowScene *windowScene;

/* class methods */
+ (id)accessAuthenticator;
+ (id)sharedInstance;

/* instance methods */
- (long long)_WallpaperOrientationNotForYou;
- (void)_activePostersDidChange:(id)change;
- (void)_applicationDidFinishLaunching:(id)launching;
- (void)_batterySaverModeChanged:(id)changed;
- (void)_forceUpdateToSpringBoardInterfaceOrientationWithAnimationDuration:(double)duration;
- (void)_ingestPrimaryWallpaperLayersSnapshotIOSurface:(id)iosurface floatingWallpaperLayerSnapshotIOSurface:(id)iosurface snapshotScale:(double)scale traitCollection:(id)collection withCompletion:(id /* block */)completion;
- (_Bool)_isAcceptingOrientationChangesFromSource:(long long)source;
- (void)_kickPosterBoard;
- (void)_motionEffectsChanged;
- (void)_noteSignificantTimeChanged:(id)changed;
- (void)_posterBoardServiceDied:(id)died;
- (void)_posterConfigurationAssociatedConfigurationDidChange:(id)change;
- (void)_posterDidUpdate:(id)update;
- (void)_reloadWallpaperAndFlushCaches:(_Bool)caches completionHandler:(id /* block */)handler;
- (void)_saveWallpaperAggdKeysForLocations:(long long)locations withConfiguration:(id)configuration;
- (void)_saveWallpaperCoreAnalyticsForLocations:(long long)locations withConfiguration:(id)configuration;
- (CGRect)_screenBoundsForOrientation:(long long)orientation;
- (void)_setupPosterBoardServiceNotifications;
- (void)_snapshotScene:(id)scene withOptions:(long long)options traitCollection:(id)collection completion:(id /* block */)completion;
- (void)_updateForLockScreenPosterConfiguration:(id)configuration homeScreenPosterConfiguration:(id)configuration;
- (void)_updateScreenBlanked;
- (void)_updateWallpaperForLocations:(long long)locations options:(unsigned long long)options wallpaperMode:(long long)mode withCompletion:(id /* block */)completion;
- (void)_updateWallpaperForLocations:(long long)locations options:(unsigned long long)options withCompletion:(id /* block */)completion;
- (id)_wallpaperViewForVariant:(long long)variant;
- (id)_window;
- (void)activateOrientationSource:(long long)source;
- (void)activeActivityDidChangeForManager:(id)manager;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)orientation willAnimateWithDuration:(double)duration fromOrientation:(long long)orientation;
- (id)activeInterfaceOrientationSourcesDescriptions;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)orientation;
- (long long)activeOrientationSource;
- (long long)activeVariant;
- (void)addObserver:(id)observer forVariant:(long long)variant;
- (void)addReachabilityObserver:(id)observer;
- (void)addWallpaperOverlay:(id)overlay;
- (id)averageColorForVariant:(long long)variant;
- (id)averageColorInRect:(CGRect)rect forVariant:(long long)variant;
- (id)averageColorInRect:(CGRect)rect forVariant:(long long)variant withSmudgeRadius:(double)radius;
- (id)batterySaverAnimationAssertion;
- (id)cachingIdentifier;
- (void)cancelInProcessAnimations;
- (double)contrastForVariant:(long long)variant;
- (double)contrastInRect:(CGRect)rect forVariant:(long long)variant;
- (id)createWallpaperFloatingViewForReason:(id)reason ignoreReplica:(_Bool)replica;
- (PBUIWallpaperStyleTransitionState)currentHomescreenStyleTransitionState;
- (void)deactivateOrientationSource:(long long)source;
- (void)dealloc;
- (long long)defaultInterfaceOrientationForSource:(long long)source;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (double)effectiveReachabilityYOffset;
- (id)embeddedWindowScene;
- (id)fakeBlurViewOverrideTraitCollection;
- (_Bool)homeScreenPosterMirrorsLock;
- (double)homescreenWallpaperScale;
- (id)init;
- (id)initWithWallpaperConfigurationManager:(id)manager;
- (id)initWithWallpaperConfigurationManager:(id)manager cachingIdentifier:(id)identifier;
- (id)initWithWindowScene:(id)scene orientation:(long long)orientation variant:(long long)variant wallpaperConfigurationManager:(id)manager cachingIdentifier:(id)identifier;
- (id)irisWallpaperPlayer;
- (_Bool)isWindowIgnoredForReachability:(id)reachability;
- (id)legibilityProvider;
- (id)legibilitySettingsForVariant:(long long)variant;
- (double)lockscreenWallpaperScale;
- (double)minimumHomescreenWallpaperScale;
- (double)minimumLockscreenWallpaperScale;
- (id)newFakeBlurViewForVariant:(long long)variant style:(long long)style transformOptions:(unsigned long long)options;
- (void)orientationSource:(long long)source didRotateFromInterfaceOrientation:(long long)orientation;
- (void)orientationSource:(long long)source willAnimateRotationToInterfaceOrientation:(long long)orientation duration:(double)duration;
- (void)orientationSource:(long long)source willRotateToInterfaceOrientation:(long long)orientation duration:(double)duration;
- (_Bool)posterHandlesWakeAnimation;
- (void)preheatWallpaperForVariant:(long long)variant;
- (id)presenter;
- (void)providerLegibilitySettingsChanged:(id)changed;
- (void)removeObserver:(id)observer forVariant:(long long)variant;
- (void)removeReachabilityObserver:(id)observer;
- (void)removeWallpaperOverlay:(id)overlay;
- (_Bool)removeWallpaperStyleForPriority:(long long)priority forVariant:(long long)variant withAnimationFactory:(id)factory;
- (id)requireWallpaperRasterizationWithReason:(id)reason;
- (id)requireWallpaperWithReason:(id)reason;
- (id)scenesForBacklightSession;
- (void)setActiveVariant:(long long)variant;
- (void)setActiveVariant:(long long)variant withOutAnimationFactory:(id)factory inAnimationFactory:(id)factory completion:(id /* block */)completion;
- (void)setBatterySaverAnimationAssertion:(id)assertion;
- (void)setFakeBlurViewOverrideTraitCollection:(id)collection;
- (id)setHomescreenWallpaperScale:(double)scale withAnimationFactory:(id)factory;
- (void)setLockscreenOnlyWallpaperAlpha:(double)alpha;
- (id)setLockscreenWallpaperScale:(double)scale withAnimationFactory:(id)factory;
- (void)setOrientationProvider:(id)provider forSource:(long long)source;
- (void)setWallpaperAggdLogger:(id)logger;
- (void)setWallpaperCoreAnalyticsLogger:(id)logger;
- (id)setWallpaperFloatingLayerContainerView:(id)view forReason:(id)reason withAnimationFactory:(id)factory;
- (void)setWallpaperHidden:(_Bool)hidden variant:(long long)variant reason:(id)reason;
- (void)setWallpaperObscured:(_Bool)obscured;
- (void)setWallpaperPresentingDelegate:(id)delegate;
- (_Bool)setWallpaperStyle:(long long)style forPriority:(long long)priority forVariant:(long long)variant withAnimationFactory:(id)factory;
- (void)setWallpaperStyleAnimationAssertion:(id)assertion;
- (_Bool)setWallpaperStyleTransitionState:(PBUIWallpaperStyleTransitionState)state forPriority:(long long)priority forVariant:(long long)variant withAnimationFactory:(id)factory;
- (void)setWindowLevel:(double)level;
- (void)setWindowScene:(id)scene;
- (void)settings:(id)settings changedValueForKey:(id)key;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)suspendWallpaperAnimationForReason:(id)reason;
- (void)triggerPosterSignificantEvent;
- (void)updateIrisWallpaperForInteractiveMode;
- (_Bool)updateIrisWallpaperForStaticMode;
- (void)updateOrientationAfterSourceChange;
- (void)updatePosterSwitcherSnapshots;
- (void)updateWallpaperAnimationWithIconFlyInTension:(double)tension friction:(double)friction;
- (void)updateWallpaperAnimationWithProgress:(double)progress;
- (void)updateWallpaperAnimationWithWakeSourceIsSwipeToUnlock:(_Bool)unlock;
- (void)updateWallpaperForLocations:(long long)locations wallpaperMode:(long long)mode withCompletion:(id /* block */)completion;
- (void)updateWallpaperForLocations:(long long)locations withCompletion:(id /* block */)completion;
- (id)wallpaperAggdLogger;
- (id)wallpaperConfigurationManager;
- (id)wallpaperCoreAnalyticsLogger;
- (id)wallpaperGestureRecognizer;
- (void)wallpaperPresenter:(id)presenter didChangeWallpaperForLocations:(long long)locations withConfiguration:(id)configuration;
- (long long)wallpaperPresenter:(id)presenter requestsOrientationWithRefresh:(_Bool)refresh;
- (void)wallpaperPresenterDidCompleteWallpaperChange:(id)change;
- (id)wallpaperPresentingDelegate;
- (void)wallpaperServer:(id)server fetchContentCutoutBoundsForVariant:(long long)variant orientation:(long long)orientation completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchLimitedOcclusionBoundsForOrientation:(long long)orientation completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchLockScreenContentCutoutBoundsForOrientation:(long long)orientation completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchLockScreenMaximalContentCutoutBoundsForOrientation:(long long)orientation completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchLockScreenTimeBoundsForOrientation:(long long)orientation completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchObscurableBoundsForOrientation:(long long)orientation completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchOriginalImageDataForVariant:(long long)variant completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchOriginalVideoURLDataForVariant:(long long)variant completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchSignificantEventsCounterForPosterWithIdentifier:(id)identifier completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server fetchThumbnailDataForVariant:(long long)variant completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server restoreDefaultWallpaperWithCompletionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server setWallpaperColor:(id)color darkColor:(id)color forVariants:(long long)variants completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server setWallpaperColorName:(id)name forVariants:(long long)variants completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server setWallpaperGradient:(id)gradient forVariants:(long long)variants completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server setWallpaperVideoWithWallpaperMode:(id)mode cropRect:(CGRect)rect wallpaperMode:(long long)mode completionHandler:(id /* block */)handler;
- (void)wallpaperServer:(id)server triggerPosterSignificantEventCompletionHandler:(id /* block */)handler;
- (id)wallpaperStyleAnimationAssertion;
- (id)wallpaperView:(id)view wallpaperConfigurationIncludingValueTypes:(unsigned long long)types;
- (void)willAnimateRotationToInterfaceOrientation:(long long)orientation duration:(double)duration;
- (double)windowLevel;
- (id)windowScene;

@end

#endif /* SBWallpaperController_h */